INSERT INTO `core_labels` (`identifier`, `lang_code`, `label`) VALUES
('inp_search', 'de', 'Suche...'),
('lbl_blog_posts_latest', 'de', 'Neueste Blog-Beiträge'),
('lbl_email', 'de', 'E-Mail'),
('lbl_list', 'de', 'Liste'),
('lbl_map', 'de', 'Karte'),
('lbl_message', 'de', 'Nachricht'),
('lbl_name', 'de', 'Name'),
('lbl_network', 'de', 'Netzwerk'),
('lbl_next', 'de', 'Weiter'),
('lbl_object', 'de', 'Objekt'),
('lbl_objects', 'de', 'Objekten'),
('lbl_password', 'de', 'Passwort'),
('lbl_previous', 'de', 'Zurück'),
('lbl_read_more', 'de', 'Weiterlesen'),
('lbl_reference', 'de', 'Referenz'),
('lbl_references', 'de', 'Referenzen'),
('lbl_search', 'de', 'Suche'),
('lbl_send', 'de', 'Absenden'),
('lbl_start_over', 'de', 'Neu anfangen'),
('lbl_uname', 'de', 'Nutzername'),
('lbl_username', 'de', 'Nutzername');
