INSERT INTO `core_labels` (`identifier`, `lang_code`, `label`) VALUES
('conf_active', 'en', 'Are you sure you which to set this item to active?'),
('conf_backup_restore', 'en', 'Are you sure you wish to restore the backup named <strong>[V][name]</strong> dating from <strong>[V][date] [V][time]</strong>?'),
('conf_cleanup_labels', 'en', 'Are you sure you want to cleanup all unused labels?'),
('conf_email_opt_out', 'en', 'You are about to unsubscribe for the email address <strong>[V][email]</strong>, are you sure?'),
('conf_general', 'en', 'Are you sure you wish to delete this item?'),
('conf_inactive', 'en', 'Are you sure you which to set this item to inactive?'),
('conf_locked_content', 'en', 'You are about to close a form. Any unsaved changes you\'ve made will be lost. Are you sure you want to continue?'),
('conf_locked_page', 'en', 'You are about to leave this page. Any unsaved changes you\'ve made will be lost. Are you sure you want to leave this page?'),
('conf_message_all', 'en', 'You are about to start a conversation with <strong>[V][count] participants</strong>. Continue?'),
('conf_message_all_individual', 'en', 'You are about to start <strong>[V][count] individual</strong> conversations. Continue?'),
('conf_newsletter_send', 'en', 'Are you sure you wish to send this newsletter to <strong>[V][count]</strong> recipients?'),
('conf_truncate', 'en', 'Are you sure you wish to truncate the whole table?'),
('inf_added_by_on', 'en', 'Added by [V][name] on [V][date]'),
('inf_api_welcome', 'en', 'Welcome to the [D][name] [V][api_name] API. For more information visit [V][api_url].'),
('inf_backup_download', 'en', 'Download backup file if backup method permits.'),
('inf_clearance_required', 'en', 'Clearance required'),
('inf_clearance_required_not', 'en', 'No user clearance required'),
('inf_date_now', 'en', 'Present Date'),
('inf_edit_date', 'en', 'Add/Edit date'),
('inf_edit_html', 'en', 'Add/Edit HTML'),
('inf_edit_script', 'en', 'Add/Edit script'),
('inf_edit_style', 'en', 'Add/Edit style'),
('inf_edit_tags', 'en', 'Add/Edit tags'),
('inf_editor_tools_activate', 'en', 'Select text to open the editor tools.'),
('inf_email_as_username', 'en', 'Use email as username.'),
('inf_email_import_guideline', 'en', 'To input multiple email addresses each email address has to be on a new line.'),
('inf_field_sub_table', 'en', 'Use table for possible selection values to use with this field.'),
('inf_filter_and', 'en', 'Reduce results of the filters (<em>n</em>) on the left.'),
('inf_filter_or', 'en', 'Add to the results of the filters (<em>n</em>) on the left.'),
('inf_form_field_required', 'en', 'Mark this field as required'),
('inf_generate_password', 'en', 'Generate a new password'),
('inf_height_full', 'en', 'Match module height with the browser.'),
('inf_jobs_run', 'en', 'Start Job Scheduler'),
('inf_jobs_stop', 'en', 'Stop Job Scheduler'),
('inf_last_activity', 'en', 'Last activity'),
('inf_login_required', 'en', 'Login required'),
('inf_login_required_not', 'en', 'No login required'),
('inf_new_window', 'en', 'Opens in new window'),
('inf_none', 'en', 'None'),
('inf_object_interaction_script', 'en', 'Use variable \'stage\' to target the main stage, use variable objects[\'object name\'] to target one of the objects.'),
('inf_page_is_index_fallback', 'en', 'This page is marked as an index or fallback page.'),
('inf_preview', 'en', 'Preview'),
('inf_preview_paragraphs', 'en', 'Number of paragraphs for preview '),
('inf_publish_in_header', 'en', 'Publish in header'),
('inf_publish_in_header_not', 'en', 'Do not publish in header'),
('inf_remove_empty_fields', 'en', 'Remove empty fields'),
('inf_save_and_edit_field', 'en', 'This field depends on other input, first save, then edit.'),
('inf_save_and_edit_section', 'en', 'This section depends on other input, first save, then edit.'),
('inf_select_above_and_show', 'en', 'Make a selection above to view the possible options.'),
('inf_send_confirmation_email', 'en', 'Send a confirmation email with login information'),
('inf_set_user_clearance', 'en', 'Set user clearance'),
('inf_tags_tag', 'en', '[V][count] items tagged with <strong>[V][tag]</strong>.'),
('inf_tschuifje_date_max', 'en', 'Select from start date to <strong>end date</strong>.'),
('inf_tschuifje_date_min', 'en', 'Select from <strong>start date</strong> to end date.'),
('inf_tschuifje_move_left', 'en', '<strong>Move</strong> selection <strong>back</strong> in time.'),
('inf_tschuifje_move_right', 'en', '<strong>Move</strong> selection <strong>forward</strong> in time.'),
('inf_tschuifje_pause', 'en', '<strong>Pause</strong> animation.'),
('inf_tschuifje_play', 'en', '<strong>Animate</strong> selection with the specified amount of time <strong>per second</strong>.'),
('inf_tschuifje_speed_amount', 'en', 'Move or animate selection with this specific <strong>amount</strong> of time.'),
('inf_tschuifje_speed_reverse', 'en', 'Play selection <strong>backwards in time</strong>.'),
('inf_tschuifje_speed_unit', 'en', 'Move or animate selection with this specific amount of <Strong>time</strong>.'),
('inf_tschuifje_stop', 'en', '<strong>Stop</strong> animation and <strong>reset</strong> selection to its original state.'),
('inf_view_position_mark', 'en', 'Mark the default view position.'),
('inf_zoom_auto', 'en', 'Find a suitable zoom level matching the viewable area.'),
('inp_search', 'en', 'Search...'),
('lbl_absolute', 'en', 'Absolute'),
('lbl_abstract', 'en', 'Abstract'),
('lbl_accept', 'en', 'Accept'),
('lbl_access', 'en', 'Access'),
('lbl_account', 'en', 'Account'),
('lbl_action', 'en', 'Action'),
('lbl_actions', 'en', 'Actions'),
('lbl_active', 'en', 'Active'),
('lbl_add', 'en', 'Add'),
('lbl_add_comment', 'en', 'Add Comment'),
('lbl_added', 'en', 'Added'),
('lbl_address', 'en', 'Address'),
('lbl_address_number', 'en', 'Address Number'),
('lbl_address_number_affix', 'en', 'Address Number Affix'),
('lbl_admin', 'en', 'Admin'),
('lbl_advanced', 'en', 'Advanced'),
('lbl_affix', 'en', 'Affix'),
('lbl_age', 'en', 'Age'),
('lbl_algorithm', 'en', 'Algorithm'),
('lbl_allow', 'en', 'Allow'),
('lbl_always', 'en', 'Always'),
('lbl_amount', 'en', 'Amount'),
('lbl_analyse', 'en', 'Analyse'),
('lbl_analysis', 'en', 'Analysis'),
('lbl_analytics_account', 'en', 'Analytics Account'),
('lbl_any', 'en', 'Any'),
('lbl_api', 'en', 'API'),
('lbl_api_client', 'en', 'API Client'),
('lbl_api_clients', 'en', 'API Clients'),
('lbl_apis', 'en', 'APIs'),
('lbl_appearance', 'en', 'Appearance'),
('lbl_append', 'en', 'Append'),
('lbl_apply', 'en', 'Apply'),
('lbl_archive', 'en', 'Archive'),
('lbl_area', 'en', 'Area'),
('lbl_ascending', 'en', 'Ascending'),
('lbl_attribution', 'en', 'Attribution'),
('lbl_audited', 'en', 'Audited'),
('lbl_authentication', 'en', 'Authentication'),
('lbl_available', 'en', 'Available'),
('lbl_back', 'en', 'Back'),
('lbl_background_color', 'en', 'Background Colour'),
('lbl_backup', 'en', 'Backup'),
('lbl_backup_1100cc', 'en', 'Backup 1100CC'),
('lbl_bank', 'en', 'Bank'),
('lbl_bank_nr', 'en', 'Bank #'),
('lbl_biography', 'en', 'Biography'),
('lbl_blog', 'en', 'Blog'),
('lbl_blog_comments', 'en', 'Blog Comments'),
('lbl_blog_post', 'en', 'Blog Post'),
('lbl_blog_posts', 'en', 'Blog Posts'),
('lbl_body', 'en', 'Body'),
('lbl_both', 'en', 'Both'),
('lbl_bounced', 'en', 'Bounced'),
('lbl_bounces', 'en', 'Bounces'),
('lbl_boundary', 'en', 'Boundary'),
('lbl_browse', 'en', 'Browse'),
('lbl_button', 'en', 'Button'),
('lbl_cache', 'en', 'Cache'),
('lbl_cache_retain', 'en', 'Cache Retain'),
('lbl_caching', 'en', 'Caching'),
('lbl_caching_external', 'en', 'Caching - External Source'),
('lbl_calendar_day', 'en', 'Day'),
('lbl_calendar_event_reminder', 'en', 'Calendar Event Reminder'),
('lbl_calendar_range', 'en', 'Overview'),
('lbl_cancel', 'en', 'Cancel'),
('lbl_category', 'en', 'Category'),
('lbl_change', 'en', 'Change'),
('lbl_changed', 'en', 'Changed'),
('lbl_chart', 'en', 'Chart'),
('lbl_check', 'en', 'Check'),
('lbl_check_returned_email', 'en', 'Check Returned Emails'),
('lbl_children', 'en', 'Descendants'),
('lbl_choice', 'en', 'Choice'),
('lbl_choice_dropdown', 'en', 'Choice Dropdown'),
('lbl_citation', 'en', 'Citation'),
('lbl_city', 'en', 'City'),
('lbl_class', 'en', 'Class'),
('lbl_classification', 'en', 'Classification'),
('lbl_classifications', 'en', 'Classifications'),
('lbl_cleanup', 'en', 'Cleanup'),
('lbl_cleanup_cache', 'en', 'Cleanup Cache'),
('lbl_cleanup_labels', 'en', 'Cleanup Labels'),
('lbl_cleanup_orphans', 'en', 'Cleanup Orphans'),
('lbl_cleanup_requests', 'en', 'Cleanup Requests'),
('lbl_clear', 'en', 'Clear All'),
('lbl_clear_selection', 'en', 'Clear Selection'),
('lbl_clearance', 'en', 'Clearance'),
('lbl_clearance_admin', 'en', 'Administrator'),
('lbl_clearance_interact', 'en', 'Interact'),
('lbl_clearance_level', 'en', 'Clearance Level'),
('lbl_clearance_under_review', 'en', 'Under Review'),
('lbl_clearance_user', 'en', 'User'),
('lbl_close', 'en', 'Close'),
('lbl_cms_only', 'en', 'CMS Only'),
('lbl_collapse', 'en', 'Collapse'),
('lbl_color', 'en', 'Colour'),
('lbl_columns', 'en', 'Columns'),
('lbl_combined', 'en', 'Combined'),
('lbl_comment', 'en', 'Comment'),
('lbl_commit', 'en', 'Commit'),
('lbl_communication', 'en', 'Communication'),
('lbl_computer', 'en', 'Computer'),
('lbl_condition', 'en', 'Condition'),
('lbl_conditions', 'en', 'Conditions'),
('lbl_configuration', 'en', 'Configuration'),
('lbl_confirmation', 'en', 'Confirmation'),
('lbl_connection', 'en', 'Connection'),
('lbl_constant', 'en', 'Constant'),
('lbl_content', 'en', 'Content'),
('lbl_context', 'en', 'Context'),
('lbl_controls', 'en', 'Controls'),
('lbl_conversation', 'en', 'Conversation'),
('lbl_copy_from', 'en', 'Copy From'),
('lbl_count', 'en', 'Count'),
('lbl_country', 'en', 'Country'),
('lbl_create', 'en', 'Create'),
('lbl_css', 'en', 'CSS'),
('lbl_custom', 'en', 'Custom'),
('lbl_data', 'en', 'Data'),
('lbl_database', 'en', 'Database'),
('lbl_date', 'en', 'Date'),
('lbl_date_end', 'en', 'Date End'),
('lbl_date_from', 'en', 'Date From'),
('lbl_date_range', 'en', 'Date Range'),
('lbl_date_start', 'en', 'Date Start'),
('lbl_date_to', 'en', 'Date To'),
('lbl_default', 'en', 'Default'),
('lbl_defaults', 'en', 'Defaults'),
('lbl_define', 'en', 'Define'),
('lbl_delay', 'en', 'Delay'),
('lbl_delete', 'en', 'Delete'),
('lbl_deleted', 'en', 'Deleted'),
('lbl_demo', 'en', 'Demo'),
('lbl_descending', 'en', 'Descending'),
('lbl_description', 'en', 'Description'),
('lbl_design', 'en', 'Design'),
('lbl_device', 'en', 'Device'),
('lbl_directory', 'en', 'Directory'),
('lbl_discard', 'en', 'Discard'),
('lbl_discuss', 'en', 'Discuss'),
('lbl_discussion', 'en', 'Discussion'),
('lbl_discussion_topic', 'en', 'Topic'),
('lbl_display', 'en', 'Display'),
('lbl_display_pixel', 'en', 'Pixel'),
('lbl_display_vector', 'en', 'Vector'),
('lbl_documentation', 'en', 'Documentation'),
('lbl_download', 'en', 'Download'),
('lbl_draft', 'en', 'Draft'),
('lbl_duration', 'en', 'Duration'),
('lbl_edit', 'en', 'Edit'),
('lbl_edited', 'en', 'Edited'),
('lbl_editor', 'en', 'Editor'),
('lbl_effect_blur', 'en', 'Blur'),
('lbl_effect_default', 'en', 'Default Effect'),
('lbl_effect_enlarge', 'en', 'Enlarge'),
('lbl_effect_hover', 'en', 'Hover Effect'),
('lbl_effect_shadow', 'en', 'Drop Shadow'),
('lbl_effect_shake', 'en', 'Shake'),
('lbl_effect_tilt_left', 'en', 'Tilt Left'),
('lbl_effect_tilt_right', 'en', 'Tilt Right'),
('lbl_email', 'en', 'Email'),
('lbl_email_1100cc', 'en', 'System Email'),
('lbl_email_1100cc_host', 'en', 'Email Host'),
('lbl_email_1100cc_password', 'en', 'Email Password'),
('lbl_email_confirm', 'en', 'Confirmation Email'),
('lbl_email_footer', 'en', 'Email Footer'),
('lbl_email_header', 'en', 'Email Header'),
('lbl_email_manager', 'en', 'Email Manager'),
('lbl_email_me', 'en', 'Me'),
('lbl_emphasis', 'en', 'Emphasis'),
('lbl_empty', 'en', 'Empty'),
('lbl_enabled', 'en', 'Enabled'),
('lbl_end', 'en', 'End'),
('lbl_equals', 'en', 'Equals'),
('lbl_exclude', 'en', 'Exclude'),
('lbl_excluding', 'en', 'Excluding'),
('lbl_executed', 'en', 'Executed'),
('lbl_explore', 'en', 'Explore'),
('lbl_export', 'en', 'Export'),
('lbl_extra', 'en', 'Extra'),
('lbl_facebook', 'en', 'Facebook'),
('lbl_fade', 'en', 'Fade'),
('lbl_fallback_page', 'en', 'Fallback Page'),
('lbl_fax', 'en', 'Fax'),
('lbl_field', 'en', 'Field'),
('lbl_field_address', 'en', 'Address Field'),
('lbl_field_date', 'en', 'Date Field'),
('lbl_field_email', 'en', 'Email Field'),
('lbl_field_surname', 'en', 'Surname Field'),
('lbl_fields', 'en', 'Fields'),
('lbl_file', 'en', 'File'),
('lbl_file_type', 'en', 'File Type'),
('lbl_filename', 'en', 'Filename'),
('lbl_files', 'en', 'Files'),
('lbl_filter', 'en', 'Filter'),
('lbl_filter_and', 'en', 'Reduction Filter'),
('lbl_filter_or', 'en', 'Addition Filter'),
('lbl_find_replace', 'en', 'Find & Replace'),
('lbl_focus', 'en', 'Focus'),
('lbl_force', 'en', 'Force'),
('lbl_form', 'en', 'Form'),
('lbl_form_submission', 'en', 'Form Submission'),
('lbl_form_submissions', 'en', 'Form Submissions'),
('lbl_format', 'en', 'Format'),
('lbl_formatting', 'en', 'Formatting'),
('lbl_frame', 'en', 'Frame'),
('lbl_from', 'en', 'From'),
('lbl_general', 'en', 'General'),
('lbl_god_mode', 'en', 'God Mode'),
('lbl_head_tags', 'en', 'Head Tags'),
('lbl_height', 'en', 'Height'),
('lbl_height_full', 'en', 'Full Height'),
('lbl_hide_menu', 'en', 'Hide Menu'),
('lbl_highlight', 'en', 'Highlight'),
('lbl_history', 'en', 'History'),
('lbl_host_name', 'en', 'Hostname'),
('lbl_hotspot', 'en', 'Hotspot'),
('lbl_html', 'en', 'HTML'),
('lbl_icon', 'en', 'Icon'),
('lbl_identifier', 'en', 'Identifier'),
('lbl_ignore', 'en', 'Ignore'),
('lbl_image', 'en', 'Image'),
('lbl_images', 'en', 'Images'),
('lbl_import', 'en', 'Import'),
('lbl_in_selection', 'en', 'In Selection'),
('lbl_inactive', 'en', 'Inactive'),
('lbl_inbox', 'en', 'Inbox'),
('lbl_include', 'en', 'Include'),
('lbl_index_page', 'en', 'Index Page'),
('lbl_info', 'en', 'Info'),
('lbl_information', 'en', 'Information'),
('lbl_input_controller', 'en', 'Input Controller'),
('lbl_interact', 'en', 'Interact'),
('lbl_interface', 'en', 'Interface'),
('lbl_internal_tag', 'en', 'Internal Tag'),
('lbl_internal_tags', 'en', 'Internal Tags'),
('lbl_interval', 'en', 'Interval'),
('lbl_label', 'en', 'Label'),
('lbl_labeler', 'en', 'Labeler'),
('lbl_language', 'en', 'Language'),
('lbl_last_activity', 'en', 'Last Activity'),
('lbl_layout', 'en', 'Layout'),
('lbl_limit', 'en', 'Limit'),
('lbl_link', 'en', 'Link'),
('lbl_links', 'en', 'Links'),
('lbl_list', 'en', 'List'),
('lbl_live', 'en', 'Live'),
('lbl_load_more', 'en', 'Load more'),
('lbl_location', 'en', 'Location'),
('lbl_locations', 'en', 'Locations'),
('lbl_lock', 'en', 'Lock'),
('lbl_locked', 'en', 'Locked'),
('lbl_log', 'en', 'Log'),
('lbl_logging', 'en', 'Logging'),
('lbl_login', 'en', 'Login'),
('lbl_login_recover', 'en', 'Recover Login'),
('lbl_login_welcome', 'en', 'Set Password'),
('lbl_logout', 'en', 'Log Out'),
('lbl_main', 'en', 'Main'),
('lbl_manage', 'en', 'Manage'),
('lbl_manual', 'en', 'Manual'),
('lbl_map', 'en', 'Map'),
('lbl_mark', 'en', 'Mark'),
('lbl_marked', 'en', 'Marked'),
('lbl_masked', 'en', 'Masked'),
('lbl_master_page', 'en', 'Master Page'),
('lbl_media', 'en', 'Media'),
('lbl_media_replace_occurrences', 'en', 'Replace Occurrences With'),
('lbl_media_type', 'en', 'Media Type'),
('lbl_merge', 'en', 'Merge'),
('lbl_message', 'en', 'Message'),
('lbl_message_all', 'en', 'Message Everyone'),
('lbl_message_all_individual', 'en', 'Message Everyone (Individually)'),
('lbl_message_count', 'en', 'Length'),
('lbl_message_new', 'en', 'New Message'),
('lbl_message_personal', 'en', 'Personal Message'),
('lbl_message_system', 'en', 'System Message'),
('lbl_message_type', 'en', 'Message Type'),
('lbl_messaging', 'en', 'Messages'),
('lbl_messaging_email_me', 'en', 'Email Me'),
('lbl_messaging_new', 'en', 'New Messages'),
('lbl_mode', 'en', 'Mode'),
('lbl_model', 'en', 'Model'),
('lbl_module', 'en', 'Module'),
('lbl_modules', 'en', 'Modules'),
('lbl_modules_installed', 'en', 'Modules Installed'),
('lbl_month', 'en', 'Month'),
('lbl_multi_select', 'en', 'Multi Select'),
('lbl_multiple', 'en', 'Multiple'),
('lbl_multiply', 'en', 'Multiply'),
('lbl_multiply_with', 'en', 'Multiply with'),
('lbl_name', 'en', 'Name'),
('lbl_name_display', 'en', 'Display Name'),
('lbl_name_insertion', 'en', 'Name Insertion'),
('lbl_network', 'en', 'Network'),
('lbl_new', 'en', 'New'),
('lbl_next', 'en', 'Next'),
('lbl_no', 'en', 'No'),
('lbl_no_effect', 'en', 'No Effect'),
('lbl_no_name', 'en', 'No Name'),
('lbl_node', 'en', 'Node'),
('lbl_nodes', 'en', 'Nodes'),
('lbl_none', 'en', 'None'),
('lbl_normalised', 'en', 'Normalised'),
('lbl_not_empty', 'en', 'Not Empty'),
('lbl_notification', 'en', 'Notification'),
('lbl_obfuscate', 'en', 'Obfuscate'),
('lbl_object', 'en', 'Object'),
('lbl_object_interaction_object', 'en', 'Object'),
('lbl_object_interaction_objects', 'en', 'Objects'),
('lbl_object_interaction_stage', 'en', 'Stage'),
('lbl_object_interaction_stages', 'en', 'Stages'),
('lbl_objects', 'en', 'Objects'),
('lbl_offset', 'en', 'Offset'),
('lbl_opacity', 'en', 'Opacity'),
('lbl_open_site', 'en', 'Site'),
('lbl_opt_out', 'en', 'Opt Out'),
('lbl_optional', 'en', 'Optional'),
('lbl_options', 'en', 'Options'),
('lbl_order', 'en', 'Order'),
('lbl_organise', 'en', 'Organise'),
('lbl_other', 'en', 'Other'),
('lbl_output', 'en', 'Output'),
('lbl_overview', 'en', 'Overview'),
('lbl_page', 'en', 'Page'),
('lbl_page_clearance', 'en', 'Page Clearance'),
('lbl_pages', 'en', 'Pages'),
('lbl_parent', 'en', 'Ascendant'),
('lbl_parent_name', 'en', 'Ascendant Name'),
('lbl_participants', 'en', 'Participants'),
('lbl_passkey', 'en', 'Passkey'),
('lbl_passkey_regenerate', 'en', 'Regenerate Passkey'),
('lbl_password', 'en', 'Password'),
('lbl_password_reset', 'en', 'Reset Password'),
('lbl_past', 'en', 'Past'),
('lbl_path', 'en', 'Path'),
('lbl_performance', 'en', 'Performance'),
('lbl_period', 'en', 'Period'),
('lbl_personal', 'en', 'Personal'),
('lbl_phone', 'en', 'Phone'),
('lbl_ping', 'en', 'Ping'),
('lbl_pingback', 'en', 'Pingback'),
('lbl_poll', 'en', 'Poll'),
('lbl_poll_sets', 'en', 'Poll Sets'),
('lbl_polls', 'en', 'Polls'),
('lbl_popup', 'en', 'Popup'),
('lbl_position', 'en', 'Position'),
('lbl_posted_by', 'en', 'Posted By'),
('lbl_prefix', 'en', 'Prefix'),
('lbl_present', 'en', 'Present'),
('lbl_previous', 'en', 'Previous'),
('lbl_price', 'en', 'Price'),
('lbl_print', 'en', 'Print'),
('lbl_private', 'en', 'Private'),
('lbl_product', 'en', 'Product'),
('lbl_project', 'en', 'Project'),
('lbl_projects', 'en', 'Projects'),
('lbl_properties', 'en', 'Properties'),
('lbl_publish', 'en', 'Publish'),
('lbl_read_more', 'en', 'Continue reading'),
('lbl_recipients', 'en', 'Recipients'),
('lbl_redirect_page', 'en', 'Redirect Page'),
('lbl_reference', 'en', 'Reference'),
('lbl_referenced', 'en', 'Cross-Referenced'),
('lbl_references', 'en', 'References'),
('lbl_referencing', 'en', 'Cross-Referencing'),
('lbl_referral_url', 'en', 'Referral URL'),
('lbl_register', 'en', 'Register'),
('lbl_relate', 'en', 'Relate'),
('lbl_relation', 'en', 'Relation'),
('lbl_relative', 'en', 'Relative'),
('lbl_remark', 'en', 'Remark'),
('lbl_remarks', 'en', 'Remarks'),
('lbl_reminder', 'en', 'Reminder'),
('lbl_remove', 'en', 'Remove'),
('lbl_remove_empty', 'en', 'Remove Empty'),
('lbl_replace', 'en', 'Replace'),
('lbl_reply', 'en', 'Reply'),
('lbl_required', 'en', 'Required'),
('lbl_reset', 'en', 'Reset'),
('lbl_response', 'en', 'Response'),
('lbl_restore', 'en', 'Restore'),
('lbl_result', 'en', 'Result'),
('lbl_run', 'en', 'Run'),
('lbl_run_web_service', 'en', 'Run Web Service'),
('lbl_running', 'en', 'Running'),
('lbl_save', 'en', 'Save'),
('lbl_scale', 'en', 'Scale'),
('lbl_scenario', 'en', 'Scenario'),
('lbl_scenarios', 'en', 'Scenarios'),
('lbl_scope', 'en', 'Scope'),
('lbl_script', 'en', 'Script'),
('lbl_script_hover', 'en', 'Hover Script'),
('lbl_scroll_horizontal', 'en', 'Scroll Horizontal'),
('lbl_scroll_vertical', 'en', 'Scroll Vertical'),
('lbl_search', 'en', 'Search'),
('lbl_select', 'en', 'Select'),
('lbl_select_all', 'en', 'Select All'),
('lbl_select_or_store', 'en', 'Select Or Store'),
('lbl_selection', 'en', 'Selection'),
('lbl_send', 'en', 'Send'),
('lbl_send_calendar_event_reminders', 'en', 'Send Calendar Event Reminders'),
('lbl_server_file', 'en', 'File Server'),
('lbl_server_file_sync', 'en', 'Synchronise File Server'),
('lbl_server_host', 'en', 'Host'),
('lbl_server_host_port', 'en', 'Port'),
('lbl_server_hosts', 'en', 'Hosts'),
('lbl_servers', 'en', 'Servers'),
('lbl_service', 'en', 'Service'),
('lbl_set', 'en', 'Set'),
('lbl_settings', 'en', 'Settings'),
('lbl_shape', 'en', 'Shape'),
('lbl_shape_circle', 'en', 'Circle'),
('lbl_shape_square', 'en', 'Square'),
('lbl_share', 'en', 'Share'),
('lbl_show', 'en', 'Show'),
('lbl_show_404', 'en', 'Show 404'),
('lbl_show_all', 'en', 'Show All'),
('lbl_show_menu', 'en', 'Show Menu'),
('lbl_show_system_errors', 'en', 'Show System Errors'),
('lbl_siblings', 'en', 'Siblings'),
('lbl_signup', 'en', 'Signup'),
('lbl_site_attribution', 'en', '<a href=\"[S][BASE_URL]\" target=\"_blank\">[D][name]</a>'),
('lbl_size', 'en', 'Size'),
('lbl_size_max', 'en', 'Max Size'),
('lbl_size_min', 'en', 'Min Size'),
('lbl_slide', 'en', 'Slide'),
('lbl_sliders', 'en', 'Sliders'),
('lbl_slides', 'en', 'Slides'),
('lbl_source', 'en', 'Source'),
('lbl_source_abbr', 'en', 'Src'),
('lbl_sources', 'en', 'Sources'),
('lbl_span', 'en', 'Span'),
('lbl_specify', 'en', 'Specify'),
('lbl_start', 'en', 'Start'),
('lbl_start_over', 'en', 'Start Over'),
('lbl_statistics', 'en', 'Statistics'),
('lbl_status', 'en', 'Status'),
('lbl_storage', 'en', 'Storage'),
('lbl_style', 'en', 'Style'),
('lbl_style_hover', 'en', 'Style Hover'),
('lbl_subject', 'en', 'Subject'),
('lbl_submissions', 'en', 'Submissions'),
('lbl_summary', 'en', 'Summary'),
('lbl_tag', 'en', 'Tag'),
('lbl_tag_cloud', 'en', 'Tag Cloud'),
('lbl_tags', 'en', 'Tags'),
('lbl_tags_hide', 'en', 'Show Less'),
('lbl_tags_show_all', 'en', 'Show More'),
('lbl_target', 'en', 'Target'),
('lbl_task', 'en', 'Task'),
('lbl_technical', 'en', 'Technical'),
('lbl_template', 'en', 'Template'),
('lbl_templates', 'en', 'Templates'),
('lbl_text', 'en', 'Text'),
('lbl_text_bold', 'en', '<strong>Bold</strong>'),
('lbl_text_color', 'en', 'Text Colour'),
('lbl_text_emphasis', 'en', 'Text Emphasis'),
('lbl_text_italic', 'en', '<em>Italic</em>'),
('lbl_text_strikethrough', 'en', '<del>Strikethrough</del>'),
('lbl_theme', 'en', 'Theme'),
('lbl_threshold', 'en', 'Threshold'),
('lbl_time', 'en', 'Time'),
('lbl_timeout', 'en', 'Timeout'),
('lbl_timing', 'en', 'Timing'),
('lbl_title', 'en', 'Title'),
('lbl_to', 'en', 'To'),
('lbl_toolbar', 'en', 'Toolbar'),
('lbl_total', 'en', 'Total'),
('lbl_transition_effect', 'en', 'Tansition Effect'),
('lbl_transition_speed', 'en', 'Transition Speed'),
('lbl_twitter', 'en', 'Twitter'),
('lbl_type', 'en', 'Type'),
('lbl_types', 'en', 'Types'),
('lbl_uname', 'en', 'Username'),
('lbl_unchanged', 'en', 'Unchanged'),
('lbl_unique', 'en', 'Unique'),
('lbl_unknown', 'en', 'Unknown'),
('lbl_update', 'en', 'Update'),
('lbl_upload', 'en', 'Upload'),
('lbl_uri_translator', 'en', 'URI Translator'),
('lbl_uri_translators', 'en', 'URI Translators'),
('lbl_uris', 'en', 'URIs'),
('lbl_url', 'en', 'URL'),
('lbl_usage', 'en', 'Usage'),
('lbl_use', 'en', 'Use'),
('lbl_use_servers', 'en', 'Use Servers'),
('lbl_user', 'en', 'User'),
('lbl_user_domain', 'en', 'Domain'),
('lbl_user_group', 'en', 'User Group'),
('lbl_user_groups', 'en', 'User Groups'),
('lbl_user_my_default', 'en', 'My Default Values'),
('lbl_username', 'en', 'Username'),
('lbl_users', 'en', 'Users'),
('lbl_valid_period', 'en', 'Validity Period'),
('lbl_value', 'en', 'Value'),
('lbl_values', 'en', 'Values'),
('lbl_vat', 'en', 'VAT'),
('lbl_version', 'en', 'Version'),
('lbl_version_abbr', 'en', 'Ver'),
('lbl_view', 'en', 'View'),
('lbl_view_selection', 'en', 'View Selection'),
('lbl_visibility', 'en', 'Visibility'),
('lbl_visible', 'en', 'Visible'),
('lbl_vote', 'en', 'Vote'),
('lbl_votes', 'en', 'Votes'),
('lbl_weight', 'en', 'Weight'),
('lbl_welcome', 'en', 'Welcome'),
('lbl_widgets', 'en', 'Widgets'),
('lbl_width', 'en', 'Width'),
('lbl_width_max', 'en', 'Max Width'),
('lbl_width_min', 'en', 'Min Width'),
('lbl_word_count', 'en', 'Word Count'),
('lbl_workspace', 'en', 'Workspace'),
('lbl_workspaces', 'en', 'Workspaces'),
('lbl_year', 'en', 'Year'),
('lbl_yes', 'en', 'Yes'),
('lbl_youtube', 'en', 'Youtube'),
('lbl_zipcode', 'en', 'Zipcode'),
('lbl_zoom_auto', 'en', 'Auto Zoom'),
('lbl_zoom_default', 'en', 'Zoom Default'),
('lbl_zoom_level', 'en', 'Zoom Level'),
('lbl_zoom_levels', 'en', 'Zoom Levels'),
('lbl_zoom_max', 'en', 'Zoom Max'),
('lbl_zoom_min', 'en', 'Zoom Min'),
('lnk_archive', 'en', 'View Archive'),
('mail_account_changed', 'en', '<p>Dear [V][name],</p>\n<p>Your account details for [D][name] have been adapted.</p>\n<p>The data is now as follows:</p>\n<p>\nUsername: [V][user_name]<br />\nDomain: [V][domain]\n</p>'),
('mail_account_changed_title', 'en', 'Account details for [D][name] have changed.'),
('mail_account_login_url', 'en', '<p>Follow <a href=\"[V][url]\" target=\"_blank\">this link</a> to log in.</p>'),
('mail_account_login_url_expire', 'en', '<p>Follow <a href=\"[V][url]\" target=\"_blank\">this link</a> ([L][msg_link_expire]) to log in.</p>'),
('mail_account_new', 'en', '<p>Dear [V][name],</p>\n<p>Your account for [D][name] has been created.</p>\n<p>You can log in to your account using the following details:</p>\n<p>\nUsername: [V][user_name]<br />\nDomain: [V][domain]\n</p>'),
('mail_account_new_title', 'en', 'Account details for [D][name].'),
('mail_confirm_account', 'en', '<p>Dear [V][name],</p>\n<p>Your [D][name] account has been created.</p>\n<p>Follow <a href=\"[V][url]\">this link</a> ([L][msg_link_expire]) to confirm your registration.</p>'),
('mail_confirm_account_recover', 'en', '<p>Dear [V][name],</p>\n<p>A new password has been requested for your account on [D][name].</p>\n<p>Follow <a href=\"[V][url]\">this link</a> ([L][msg_link_expire]) to confirm the request for a new password.</p>'),
('mail_confirm_account_recover_title', 'en', 'Password request for [D][name].'),
('mail_confirm_account_title', 'en', 'Confirm your account details for [D][name].'),
('mail_confirm_account_update', 'en', '<p>Dear [V][name],</p>\n<p>Your account on [D][name] has been updated.</p>\n<p>Follow <a href=\"[V][url]\">this link</a> to confirm the changes.</p>'),
('mail_confirm_account_update_title', 'en', 'Account details update for [D][name].'),
('mail_form_submitted', 'en', 'A form has been submitted on the [D][name] website, go to the <a href=\"[V][url]\">CMS</a> to view the submission.'),
('mail_messaging_notification', 'en', '<p>Dear [V][name],</p>\n<p>You have received a new message from [D][name]. The message is in your inbox under the topic \"[V][subject]\"</p>\n<p>Click <a href=\"[V][link]\">here</a> to go to your inbox.</p>'),
('mail_messaging_notification_title', 'en', 'You\'ve received a new message on [D][name].'),
('msg_access_denied', 'en', 'You do not possess the correct credentials to be allowed access.'),
('msg_access_limit', 'en', 'The limit for false login attempts has been reached, please try again at a later time.'),
('msg_account_update_confirmed', 'en', 'Your new account details have been confirmed.'),
('msg_api_limit', 'en', 'The API request limit ([V][limit]) has been reached. Please try again later.'),
('msg_building_cache', 'en', 'Building cache'),
('msg_calendar_event_reminder_notification', 'en', 'This is a notification for the calendar event [V][name] starting on [V][date] and ending [V][date_end].\nThe event starts in [V][reminder_amount] [V][reminder_unit_name].\n\n[V][description]'),
('msg_confirm_account_mail_sent', 'en', 'A confirmation has been sent to your email address.'),
('msg_confirm_account_recover_mail_sent', 'en', 'An email has been sent to your account to recover your lost information.'),
('msg_confirm_account_update_mail_sent', 'en', 'A confirmation email has been sent to your email address.'),
('msg_contact_mail_sent', 'en', 'Contact form successfully sent: [V][from] ([V][email])'),
('msg_data_range_too_wide', 'en', 'The current data range is too wide, please narrow your selection.'),
('msg_date_incorrect', 'en', 'Date is incorrect'),
('msg_duplicate_user', 'en', 'This user already exists, please choose a different username.'),
('msg_email_opt_out_success', 'en', 'You have been successfully unsubscribed.'),
('msg_enable_cookies', 'en', 'Your session may have timed out. Refresh the page (F5) or click <a href=\"[V][url]\">here</a> to start again.'),
('msg_enable_script', 'en', 'Try to enable javascript support in your browser.'),
('msg_error', 'en', 'The actions have not been executed due to an error'),
('msg_error_database_data_field_limit', 'en', 'The database received a value from your data that is too large to store. Please check the sizes of the values you\'re submitting.'),
('msg_error_email_format', 'en', 'The supplied email address is not a correct address.'),
('msg_error_memory_limit', 'en', 'The allowed memory size of your request reached the limit of <strong>[V][amount]</strong>. Please review your request, or contact [D][email] to report any irregularities.'),
('msg_error_time_limit', 'en', 'The allowed execution time of your request reached the limit of <strong>[V][amount] seconds</strong>. Please review your request, or contact [D][email] to report any irregularities.'),
('msg_file_too_large', 'en', 'File is too large.'),
('msg_file_upload_successful', 'en', 'File upload successful.'),
('msg_form_submitted', 'en', 'Form is submitted successfully.'),
('msg_illegal_action', 'en', 'The current action could not complete due to illegal parameters.'),
('msg_invalid_email', 'en', 'Invalid email address.'),
('msg_invalid_file_type', 'en', 'Invalid file type.'),
('msg_invalid_file_type_specific', 'en', 'Invalid file type. Please provide a file of the type <strong>[V][type]</strong>.'),
('msg_item_already_exists', 'en', 'The item already exists.'),
('msg_link_expire', 'en', 'link will expire after being clicked'),
('msg_loading_server_data', 'en', 'Loading data from server.'),
('msg_login_incorrect', 'en', 'Wrong username or password.'),
('msg_login_recover_confirm', 'en', '[L][msg_login_welcome]'),
('msg_login_recover_confirmed', 'en', '[L][msg_login_welcome_confirmed]'),
('msg_login_recover_link', 'en', 'Lost your password? Click <a href=\"[V][url_recover_password]\">here</a>.'),
('msg_login_recover_link_return', 'en', 'Click <a href=\"[V][url_login]\">here</a> to return to the login form.'),
('msg_login_welcome', 'en', '<p>Hi [V][name],</p>\n<p>Below are the basic account details for your [D][name] account:</p>\n<ul>\n<li>Username: [V][user_name]</li>\n<li>Email: [V][user_email]</li>\n<li>Domain: [V][domain]</li>\n</ul>\n<p>Please provide the password you want to use:</p>'),
('msg_login_welcome_confirmed', 'en', 'Your password has been confirmed. Please use your username and password to log in.'),
('msg_missing_information', 'en', 'Necessary information is missing or not correctly supplied.'),
('msg_no', 'en', 'There are no [V][name] available.'),
('msg_no_blogs', 'en', 'There are no blogs created.'),
('msg_no_calendar_events', 'en', 'There are no events.'),
('msg_no_cookie_support', 'en', 'No cookie support has been found'),
('msg_no_custom_content', 'en', 'There is no custom content created.'),
('msg_no_dashboards', 'en', 'There are no dashboards created.'),
('msg_no_data', 'en', 'No data.'),
('msg_no_directories', 'en', 'There is no directory structure created.'),
('msg_no_file_or_too_large', 'en', 'No file uploaded, or file too large (Max. [V][max_size] MB)'),
('msg_no_forms', 'en', 'There are no forms created.'),
('msg_no_language', 'en', 'There are no language profiles created.'),
('msg_no_media', 'en', 'There are no media items created.'),
('msg_no_object_interaction_objects', 'en', 'There are no objects created.'),
('msg_no_object_interaction_stages', 'en', 'There are no stages created.'),
('msg_no_options', 'en', 'No options are available.'),
('msg_no_pages', 'en', 'No pages found.'),
('msg_no_pingbacks', 'en', 'No pingbacks found'),
('msg_no_polls', 'en', 'There are no polls created.'),
('msg_no_projects', 'en', 'There are no projects created.'),
('msg_no_results', 'en', 'No results.'),
('msg_no_script_support', 'en', 'No javascript support has been found.'),
('msg_no_sliders', 'en', 'There are no sliders created.'),
('msg_no_slides', 'en', 'There are no slides created.'),
('msg_no_templates', 'en', 'There are no templates created.'),
('msg_no_user_groups', 'en', 'There are no user groups created.'),
('msg_no_users', 'en', 'There are no users created.'),
('msg_not_allowed', 'en', 'The current action is not allowed.'),
('msg_not_allowed_demo', 'en', 'The currect action is not allowed using a demo account'),
('msg_not_available', 'en', 'Not available.'),
('msg_not_found', 'en', 'The requested item is not found.'),
('msg_object_interaction_tiles_level_done', 'en', 'New zoom level has been created:'),
('msg_page_delete_is_index_fallback', 'en', 'Page cannot be deleted due to an index or fallback property.'),
('msg_page_not_found', 'en', 'The page you requested can not be found'),
('msg_page_not_found_suggestion', 'en', 'Try to go back to the page you came from or click <a href=\"[V][url]\">here</a>'),
('msg_redirect', 'en', 'You are being redirected.'),
('msg_registration_confirmed', 'en', 'Your account has been confirmed.'),
('msg_search_by_typing', 'en', 'Type to search [V][what].'),
('msg_search_no_result', 'en', 'The search returned no results.'),
('msg_search_too_short', 'en', 'Search string is too short, a minimum of 4 characters is desirable.'),
('msg_site_maintenance', 'en', '[D][name] is under maintenance.'),
('msg_site_read_only', 'en', 'You are currently looking at a READ-ONLY instance of [D][name]!'),
('msg_success', 'en', 'The action returned with success.'),
('msg_transferring', 'en', 'Transferring...'),
('msg_upload_failed', 'en', 'Upload failed.'),
('msg_wait', 'en', 'A moment please.'),
('ttl_archive', 'en', 'Archive'),
('ttl_blog', 'en', 'Blog'),
('ttl_blog_posts', 'en', 'Blog Posts'),
('ttl_blog_preview', 'en', 'Blog Preview'),
('ttl_blogs', 'en', 'Blogs'),
('ttl_calendar', 'en', 'Calendar'),
('ttl_checklists', 'en', 'Checklists'),
('ttl_cms', 'en', 'CMS'),
('ttl_cms_users', 'en', 'CMS Users'),
('ttl_comments', 'en', 'Comments'),
('ttl_contact', 'en', 'Contact'),
('ttl_content', 'en', 'Content'),
('ttl_custom_content', 'en', 'Custom Content'),
('ttl_dashboard', 'en', 'Dashboard'),
('ttl_dashboards', 'en', 'Dashboards'),
('ttl_data', 'en', 'Data'),
('ttl_details', 'en', 'Details'),
('ttl_directories', 'en', 'Directories'),
('ttl_email_manager', 'en', 'Email Manager'),
('ttl_footer', 'en', 'Footer'),
('ttl_form', 'en', 'Form'),
('ttl_forms', 'en', 'Forms'),
('ttl_header', 'en', 'Header'),
('ttl_header_dropdown', 'en', 'Header Dropdown'),
('ttl_input', 'en', 'Input'),
('ttl_invoice', 'en', 'Invoice'),
('ttl_jobs', 'en', 'Jobs'),
('ttl_labels', 'en', 'Labels'),
('ttl_language', 'en', 'Language'),
('ttl_latest_blog_posts', 'en', 'Latest Blog Posts'),
('ttl_media', 'en', 'Media'),
('ttl_messaging', 'en', 'Messaging'),
('ttl_navigation', 'en', 'Navigation'),
('ttl_newsletter_signup', 'en', 'Newsletter Signup'),
('ttl_newsletters', 'en', 'Newsletters'),
('ttl_object_interaction', 'en', 'Object Stages'),
('ttl_order', 'en', 'Order'),
('ttl_orders', 'en', 'Orders'),
('ttl_poll', 'en', 'Poll'),
('ttl_poll_sets', 'en', 'Poll Sets'),
('ttl_polls', 'en', 'Polls'),
('ttl_posts', 'en', 'Posts'),
('ttl_project_management', 'en', 'Project Management'),
('ttl_projects', 'en', 'Projects'),
('ttl_register', 'en', 'Register'),
('ttl_register_users', 'en', 'Register Users'),
('ttl_result', 'en', 'Result'),
('ttl_search', 'en', 'Search'),
('ttl_search_box', 'en', 'Search Box'),
('ttl_settings', 'en', 'Settings'),
('ttl_shop', 'en', 'Shop'),
('ttl_shop_orders', 'en', 'Shop Orders'),
('ttl_shop_products', 'en', 'Shop Products'),
('ttl_site', 'en', 'Site'),
('ttl_sitemap', 'en', 'Sitemap'),
('ttl_slider', 'en', 'Slider'),
('ttl_sliders', 'en', 'Sliders'),
('ttl_slides', 'en', 'Slides'),
('ttl_tags', 'en', 'Tags'),
('ttl_templates', 'en', 'Templates'),
('ttl_upload', 'en', 'Upload'),
('ttl_user_groups', 'en', 'User Groups'),
('ttl_user_management', 'en', 'User Management'),
('ttl_website_details', 'en', 'Website Details'),
('txt_contact_form_info', 'en', 'When you have questions, comments or suggestions for [D][name], please use the form below.'),
('txt_email_opt_out', 'en', '<p>Click <a href=\"[V][link_opt_out]\">here</a> to unsubscribe.</p>'),
('txt_newsletter_signup', 'en', 'Signup for the [D][name] newsletter.'),
('txt_trouble_viewing', 'en', 'Having trouble viewing this message? Click <a href=\"[V][link_view]\">here</a>.'),
('unit_data_boolean', 'en', 'True/False'),
('unit_data_date', 'en', 'Date'),
('unit_data_int', 'en', 'Integer'),
('unit_data_text', 'en', 'Text'),
('unit_data_varchar', 'en', 'String'),
('unit_data_xml', 'en', 'XML'),
('unit_day', 'en', 'day'),
('unit_days', 'en', 'days'),
('unit_hour', 'en', 'hour'),
('unit_hours', 'en', 'hours'),
('unit_meter', 'en', 'meter'),
('unit_milliseconds', 'en', 'milliseconds'),
('unit_minute', 'en', 'minute'),
('unit_minutes', 'en', 'minutes'),
('unit_month', 'en', 'month'),
('unit_month_april', 'en', 'April'),
('unit_month_august', 'en', 'August'),
('unit_month_december', 'en', 'December'),
('unit_month_february', 'en', 'February'),
('unit_month_january', 'en', 'January'),
('unit_month_july', 'en', 'July'),
('unit_month_june', 'en', 'June'),
('unit_month_march', 'en', 'March'),
('unit_month_may', 'en', 'May'),
('unit_month_november', 'en', 'November'),
('unit_month_october', 'en', 'October'),
('unit_month_september', 'en', 'September'),
('unit_months', 'en', 'months'),
('unit_second', 'en', 'second'),
('unit_seconds', 'en', 'seconds'),
('unit_week', 'en', 'week'),
('unit_week_day_abbr_length', 'en', '3'),
('unit_week_friday', 'en', 'Friday'),
('unit_week_monday', 'en', 'Monday'),
('unit_week_saturday', 'en', 'Saturday'),
('unit_week_sunday', 'en', 'Sunday'),
('unit_week_thursday', 'en', 'Thursday'),
('unit_week_tuesday', 'en', 'Tuesday'),
('unit_week_wednesday', 'en', 'Wednesday'),
('unit_weeks', 'en', 'weeks'),
('unit_year', 'en', 'year');
