INSERT INTO `core_labels` (`identifier`, `lang_code`, `label`) VALUES
('conf_active', 'nl', 'Weet u zeker dat u dit item op actief wilt zetten?'),
('conf_backup_restore', 'nl', 'Weet u zeker dat u de backup <strong>[V][name]</strong> met de datum <strong>[V][date] [V][time]</strong> wilt herstellen?'),
('conf_cleanup_labels', 'nl', 'Weet u zeker dat u alle ongebruikte labels wilt opruimen?'),
('conf_email_opt_out', 'nl', 'U staat op het punt zich uit te schrijven voor het emailadres  <strong>[V][email]</strong>, weet u het zeker?'),
('conf_general', 'nl', 'Weet u zeker dat u dit item wilt verwijderen?'),
('conf_inactive', 'nl', 'Weet u zeker dat u dit item op inactief wilt zetten?'),
('conf_locked_content', 'nl', 'Je staat op het punt om een formulier te sluiten. Mogelijke onopgeslagen  aanpassingen zullen verloren gaan. Weet je zeker dat je door wilt gaan?'),
('conf_locked_page', 'nl', 'Je staat op het punt deze pagina te verlaten. Mogelijke onopgeslagen  aanpassingen zullen verloren gaan. Weet je zeker dat je deze pagina wilt verlaten?'),
('conf_message_all', 'nl', 'Je staat op het punt om een conversatie te starten met <strong>[V][count] deelnemers</strong>. Doorgaan?'),
('conf_message_all_individual', 'nl', 'Je staat op het punt om <strong>[V][count] individuele</strong> conversaties te starten. Doorgaan?'),
('conf_newsletter_send', 'nl', 'Weet u zeker dat u deze nieuwsbrief naar <strong>[V][count]</strong> ontvangers wilt versturen?'),
('conf_truncate', 'nl', 'Weet u zeker dat u de hele tabel wilt legen?'),
('inf_added_by_on', 'nl', 'Toegevoegd door [V][name] op [V][date]'),
('inf_api_welcome', 'nl', 'Welkom bij de [D][name] [V][api_name] API. Voor meer informatie ga naar [V][api_url].'),
('inf_backup_download', 'nl', 'Download backupbestand als backupmethode dit toestaat.'),
('inf_clearance_required', 'nl', 'Vereist gebruikersbevoegdheid'),
('inf_clearance_required_not', 'nl', 'Vereist geen gebruikersbevoegdheid'),
('inf_date_now', 'nl', 'Actuele Datum'),
('inf_edit_date', 'nl', 'Datum toevoegen/aanpassen'),
('inf_edit_html', 'nl', 'HTML toevoegen/aanpassen'),
('inf_edit_script', 'nl', 'Script toevoegen/aanpassen'),
('inf_edit_style', 'nl', 'Stijl toevoegen/aanpassen'),
('inf_edit_tags', 'nl', 'Tags toevoegen/aanpassen'),
('inf_editor_tools_activate', 'nl', 'Selecteer tekst om de editor tools te openen.'),
('inf_email_as_username', 'nl', 'Gebruik email als gebruikersnaam.'),
('inf_email_import_guideline', 'nl', 'Voor het invoeren van meerdere emailadressen dient ieder emailadres op een nieuwe lijn te worden geplaatst.'),
('inf_field_sub_table', 'nl', 'Gebruik tabel als te selecteren waarden voor dit veld.'),
('inf_filter_and', 'nl', 'Reduceer resultaten van de filters  (<em>n</em>) aan de linkerkant.'),
('inf_filter_or', 'nl', 'Voeg resultaten toe aan de filters  (<em>n</em>) aan de linkerkant.'),
('inf_form_field_required', 'nl', 'Maak dit veld verplicht'),
('inf_generate_password', 'nl', 'Genereer een nieuw wachtwoord'),
('inf_height_full', 'nl', 'Maak de hoogte van de module gelijk met de browser.'),
('inf_jobs_run', 'nl', 'Start Jobsprogramma'),
('inf_jobs_stop', 'nl', 'Stop Jobsprogramma'),
('inf_last_activity', 'nl', 'Laatste activiteit'),
('inf_login_required', 'nl', 'Login verplicht'),
('inf_login_required_not', 'nl', 'Login niet verplicht'),
('inf_new_window', 'nl', 'Opent in nieuw scherm'),
('inf_none', 'nl', 'Geen'),
('inf_object_interaction_script', 'nl', 'Gebruik variabele \'stage\' voor het podium als doelwit, gebruik variable objects[\'object name\'] om een object te gebruiken.'),
('inf_page_is_index_fallback', 'nl', 'Deze pagina is gemarkeerd als een index- of terugvalpagina.'),
('inf_preview', 'nl', 'Preview'),
('inf_preview_paragraphs', 'nl', 'Aantal paragraven voor preview'),
('inf_publish_in_header', 'nl', 'Publiceer in header'),
('inf_publish_in_header_not', 'nl', 'Publiceer niet in header'),
('inf_remove_empty_fields', 'nl', 'Verwijder lege velden'),
('inf_save_and_edit_field', 'nl', 'Dit veld hangt van andere invoer af, eerst opslaan, dan aanpassen.'),
('inf_save_and_edit_section', 'nl', 'Dit gedeelte hangt van andere invoer af, eerst opslaan, dan aanpassen.'),
('inf_select_above_and_show', 'nl', 'Maak een selectie hierboven om de mogelijke opties te bekijken.'),
('inf_send_confirmation_email', 'nl', 'Verstuur een bevestigingsemail met login informatie'),
('inf_set_user_clearance', 'nl', 'Instellen van gebruikersbevoegdheid'),
('inf_tags_tag', 'nl', '[V][count] items getagd met <strong>[V][tag]</strong>.'),
('inf_view_position_mark', 'nl', 'Markeer de standaard zichtspositie.'),
('inf_zoom_auto', 'nl', 'Vind een geschikt zoomniveau dat het beste bij het zichtbare gebied past.'),
('inp_search', 'nl', 'Zoeken...'),
('lbl_absolute', 'nl', 'Absoluut'),
('lbl_abstract', 'nl', 'Abstract'),
('lbl_accept', 'nl', 'Accepteer'),
('lbl_access', 'nl', 'Toegang'),
('lbl_account', 'nl', 'Account'),
('lbl_action', 'nl', 'Actie'),
('lbl_actions', 'nl', 'Acties'),
('lbl_active', 'nl', 'Actief'),
('lbl_add', 'nl', 'Toevoegen'),
('lbl_add_comment', 'nl', 'Plaats Reactie'),
('lbl_added', 'nl', 'Toegevoegd'),
('lbl_address', 'nl', 'Adres'),
('lbl_address_number', 'nl', 'Huisnummer'),
('lbl_address_number_affix', 'nl', 'Huisnummer Toevoeging'),
('lbl_admin', 'nl', 'Admin'),
('lbl_advanced', 'nl', 'Geavanceerd'),
('lbl_affix', 'nl', 'Toevoegen'),
('lbl_age', 'nl', 'Leeftijd'),
('lbl_algorithm', 'nl', 'Algoritme'),
('lbl_allow', 'nl', 'Toestaan'),
('lbl_always', 'nl', 'Altijd'),
('lbl_amount', 'nl', 'Aantal'),
('lbl_analyse', 'nl', 'Analyse'),
('lbl_analysis', 'nl', 'Analyse'),
('lbl_analytics_account', 'nl', 'Analytics Account'),
('lbl_any', 'nl', 'Ieder'),
('lbl_api', 'nl', 'API'),
('lbl_api_client', 'nl', 'API Client'),
('lbl_api_clients', 'nl', 'API Clients'),
('lbl_apis', 'nl', 'API\'s'),
('lbl_appearance', 'nl', 'Uiterlijk'),
('lbl_append', 'nl', 'Toevoegen'),
('lbl_apply', 'nl', 'Toepassen'),
('lbl_archive', 'nl', 'Archief'),
('lbl_area', 'nl', 'Gebied'),
('lbl_ascending', 'nl', 'Oplopend'),
('lbl_attribution', 'nl', 'Attributie'),
('lbl_audited', 'nl', 'Geauditeerd'),
('lbl_authentication', 'nl', 'Authenticatie'),
('lbl_available', 'nl', 'Beschikbaar'),
('lbl_back', 'nl', 'Terug'),
('lbl_background_color', 'nl', 'Achtergrondkleur'),
('lbl_backup', 'nl', 'Backup'),
('lbl_backup_1100cc', 'nl', 'Backup 1100CC'),
('lbl_bank', 'nl', 'Bank'),
('lbl_bank_nr', 'nl', 'Bank #'),
('lbl_biography', 'nl', 'Biografie'),
('lbl_blog', 'nl', 'Blog'),
('lbl_blog_comments', 'nl', 'Blogreacties'),
('lbl_blog_post', 'nl', 'Blog Post'),
('lbl_blog_posts', 'nl', 'Blog Posts'),
('lbl_body', 'nl', 'Body'),
('lbl_both', 'nl', 'Beide'),
('lbl_bounced', 'nl', 'Bounced'),
('lbl_bounces', 'nl', 'Bounces'),
('lbl_boundary', 'nl', 'Grens'),
('lbl_browse', 'nl', 'Bladeren'),
('lbl_button', 'nl', 'Knop'),
('lbl_cache', 'nl', 'Cache'),
('lbl_cache_retain', 'nl', 'Cache behoud'),
('lbl_caching', 'nl', 'Caching'),
('lbl_caching_external', 'nl', 'Caching - Externe Bron'),
('lbl_calendar_day', 'nl', 'Dag'),
('lbl_calendar_event_reminder', 'nl', 'Agendapunt Herinnering'),
('lbl_calendar_range', 'nl', 'Overzicht'),
('lbl_cancel', 'nl', 'Annuleer'),
('lbl_category', 'nl', 'Categorie'),
('lbl_change', 'nl', 'Wijzig'),
('lbl_changed', 'nl', 'Veranderd'),
('lbl_chart', 'nl', 'Grafiek'),
('lbl_check', 'nl', 'Check'),
('lbl_check_returned_email', 'nl', 'Controleer Teruggekomen Emails'),
('lbl_children', 'nl', 'Afstammelingen'),
('lbl_choice', 'nl', 'Keuze'),
('lbl_choice_dropdown', 'nl', 'Keuze Uitklappen'),
('lbl_citation', 'nl', 'Citaat'),
('lbl_city', 'nl', 'Plaats'),
('lbl_class', 'nl', 'Class'),
('lbl_classification', 'nl', 'Classificatie'),
('lbl_classifications', 'nl', 'Classificaties'),
('lbl_cleanup', 'nl', 'Opschonen'),
('lbl_cleanup_cache', 'nl', 'Cache Opschonen'),
('lbl_cleanup_labels', 'nl', 'Labels Opschonen'),
('lbl_cleanup_orphans', 'nl', 'Opschonen Wezen'),
('lbl_cleanup_requests', 'nl', 'Requests Opschonen'),
('lbl_clear', 'nl', 'Verwijder Alles'),
('lbl_clear_selection', 'nl', 'Verwijder Selectie'),
('lbl_clearance', 'nl', 'Bevoegd'),
('lbl_clearance_admin', 'nl', 'Administrator'),
('lbl_clearance_interact', 'nl', 'Interact'),
('lbl_clearance_level', 'nl', 'Bevoegdheidsniveau'),
('lbl_clearance_under_review', 'nl', 'Onder Toezicht'),
('lbl_clearance_user', 'nl', 'Gebruiker'),
('lbl_close', 'nl', 'Sluiten'),
('lbl_cms_only', 'nl', 'Alleen CMS'),
('lbl_collapse', 'nl', 'Vervallen'),
('lbl_color', 'nl', 'Kleur'),
('lbl_columns', 'nl', 'Kolommen'),
('lbl_combined', 'nl', 'Gecombineerd'),
('lbl_comment', 'nl', 'Reactie'),
('lbl_commit', 'nl', 'Toepassen'),
('lbl_communication', 'nl', 'Communicatie'),
('lbl_computer', 'nl', 'Computer'),
('lbl_condition', 'nl', 'Conditie'),
('lbl_conditions', 'nl', 'Condities'),
('lbl_configuration', 'nl', 'Configuratie'),
('lbl_confirmation', 'nl', 'Bevestiging'),
('lbl_connection', 'nl', 'Connectie'),
('lbl_constant', 'nl', 'Constante'),
('lbl_content', 'nl', 'Content'),
('lbl_context', 'nl', 'Context'),
('lbl_controls', 'nl', 'Controles'),
('lbl_conversation', 'nl', 'Conversatie'),
('lbl_copy_from', 'nl', 'Kopieër Van'),
('lbl_count', 'nl', 'Tellen'),
('lbl_country', 'nl', 'Land'),
('lbl_create', 'nl', 'Creëer'),
('lbl_css', 'nl', 'CSS'),
('lbl_custom', 'nl', 'Custom'),
('lbl_data', 'nl', 'Data'),
('lbl_database', 'nl', 'Database'),
('lbl_date', 'nl', 'Datum'),
('lbl_date_end', 'nl', 'Einddatum'),
('lbl_date_from', 'nl', 'Vanaf Datum'),
('lbl_date_range', 'nl', 'Datumbereik'),
('lbl_date_start', 'nl', 'Startdatum'),
('lbl_date_to', 'nl', 'Tot Datum'),
('lbl_default', 'nl', 'Standaard'),
('lbl_defaults', 'nl', 'Standaard'),
('lbl_define', 'nl', 'Definieer'),
('lbl_delay', 'nl', 'Vertraging'),
('lbl_delete', 'nl', 'Verwijder'),
('lbl_deleted', 'nl', 'Verwijderd'),
('lbl_demo', 'nl', 'Demo'),
('lbl_descending', 'nl', 'Aflopend'),
('lbl_description', 'nl', 'Beschrijving'),
('lbl_design', 'nl', 'Vormgeving'),
('lbl_device', 'nl', 'Apparaat'),
('lbl_directory', 'nl', 'Directory'),
('lbl_discard', 'nl', 'Discard'),
('lbl_discuss', 'nl', 'Discuseer'),
('lbl_discussion', 'nl', 'Discussie'),
('lbl_discussion_topic', 'nl', 'Onderwerp'),
('lbl_display', 'nl', 'Toon'),
('lbl_display_pixel', 'nl', 'Pixel'),
('lbl_display_vector', 'nl', 'Vector'),
('lbl_documentation', 'nl', 'Documentatie'),
('lbl_download', 'nl', 'Download'),
('lbl_draft', 'nl', 'Draft'),
('lbl_duration', 'nl', 'Duratie'),
('lbl_edit', 'nl', 'Aanpassen'),
('lbl_edited', 'nl', 'Bewerkt'),
('lbl_editor', 'nl', 'Editor'),
('lbl_effect_blur', 'nl', 'Vervagen'),
('lbl_effect_default', 'nl', 'Standaard Effect'),
('lbl_effect_enlarge', 'nl', 'Vergroot'),
('lbl_effect_hover', 'nl', 'Muiseffect'),
('lbl_effect_shadow', 'nl', 'Schaduw'),
('lbl_effect_shake', 'nl', 'Schudden'),
('lbl_effect_tilt_left', 'nl', 'Kantel Links'),
('lbl_effect_tilt_right', 'nl', 'Kantel Rechts'),
('lbl_email', 'nl', 'Email'),
('lbl_email_1100cc', 'nl', 'Systeememail'),
('lbl_email_1100cc_host', 'nl', 'Email Host'),
('lbl_email_1100cc_password', 'nl', 'Email Wachtwoord'),
('lbl_email_confirm', 'nl', 'Bevestigingemail'),
('lbl_email_footer', 'nl', 'Email Footer'),
('lbl_email_header', 'nl', 'Email Header'),
('lbl_email_manager', 'nl', 'Email Manager'),
('lbl_email_me', 'nl', 'Mij'),
('lbl_emphasis', 'nl', 'Nadruk'),
('lbl_empty', 'nl', 'Leeg'),
('lbl_enabled', 'nl', 'Actief'),
('lbl_end', 'nl', 'Einde'),
('lbl_equals', 'nl', 'Gelijk Aan'),
('lbl_exclude', 'nl', 'Uitsluiten'),
('lbl_excluding', 'nl', 'Exclusief'),
('lbl_executed', 'nl', 'Uitgevoerd'),
('lbl_explore', 'nl', 'Bekijk'),
('lbl_export', 'nl', 'Exporteren'),
('lbl_extra', 'nl', 'Extra'),
('lbl_facebook', 'nl', 'Facebook'),
('lbl_fade', 'nl', 'Vervagen'),
('lbl_fallback_page', 'nl', 'Terugvalpagina'),
('lbl_fax', 'nl', 'Fax'),
('lbl_field', 'nl', 'Veld'),
('lbl_field_address', 'nl', 'Adresveld'),
('lbl_field_date', 'nl', 'Datumveld'),
('lbl_field_email', 'nl', 'Emailveld'),
('lbl_field_surname', 'nl', 'Achternaamveld'),
('lbl_fields', 'nl', 'Velden'),
('lbl_file', 'nl', 'Bestand'),
('lbl_file_type', 'nl', 'Bestandstype'),
('lbl_filename', 'nl', 'Bestandsnaam'),
('lbl_files', 'nl', 'Bestanden'),
('lbl_filter', 'nl', 'Filter'),
('lbl_filter_and', 'nl', 'Reduceerfilter'),
('lbl_filter_or', 'nl', 'Toevoegingsfilter'),
('lbl_find_replace', 'nl', 'Zoek & Vervang'),
('lbl_focus', 'nl', 'Focus'),
('lbl_force', 'nl', 'Forceer'),
('lbl_form', 'nl', 'Formulier'),
('lbl_form_submission', 'nl', 'Formulierinzending'),
('lbl_form_submissions', 'nl', 'Formulierinzendingen'),
('lbl_format', 'nl', 'Formaat'),
('lbl_formatting', 'nl', 'Opmaak'),
('lbl_frame', 'nl', 'Frame'),
('lbl_from', 'nl', 'Van'),
('lbl_general', 'nl', 'Algemeen'),
('lbl_god_mode', 'nl', 'God Modus'),
('lbl_head_tags', 'nl', 'Head Tags'),
('lbl_height', 'nl', 'Hoogte'),
('lbl_height_full', 'nl', 'Volledige Hoogte'),
('lbl_hide_menu', 'nl', 'Verberg Menu'),
('lbl_highlight', 'nl', 'Uitlichten'),
('lbl_history', 'nl', 'Geschiedenis'),
('lbl_host_name', 'nl', 'Hostname'),
('lbl_hotspot', 'nl', 'Hotspot'),
('lbl_html', 'nl', 'HTML'),
('lbl_icon', 'nl', 'Icoon'),
('lbl_identifier', 'nl', 'Identificatie'),
('lbl_ignore', 'nl', 'Negeer'),
('lbl_image', 'nl', 'Afbeelding'),
('lbl_images', 'nl', 'Afbeeldingen'),
('lbl_import', 'nl', 'Importeren'),
('lbl_in_selection', 'nl', 'In Selectie'),
('lbl_inactive', 'nl', 'Inactief'),
('lbl_inbox', 'nl', 'Inbox'),
('lbl_include', 'nl', 'Bijvoegen'),
('lbl_index_page', 'nl', 'Index Pagina'),
('lbl_info', 'nl', 'Info'),
('lbl_information', 'nl', 'Informatie'),
('lbl_input_controller', 'nl', 'Invoercontroller'),
('lbl_interact', 'nl', 'Interacteer'),
('lbl_interface', 'nl', 'Interface'),
('lbl_internal_tag', 'nl', 'Interne Tag'),
('lbl_internal_tags', 'nl', 'Interne Tags'),
('lbl_interval', 'nl', 'Interval'),
('lbl_label', 'nl', 'Label'),
('lbl_labeler', 'nl', 'Labeler'),
('lbl_language', 'nl', 'Taal'),
('lbl_last_activity', 'nl', 'Laatste Activiteit'),
('lbl_layout', 'nl', 'Opmaak'),
('lbl_limit', 'nl', 'Limiet'),
('lbl_link', 'nl', 'Link'),
('lbl_links', 'nl', 'Links'),
('lbl_list', 'nl', 'Lijst'),
('lbl_live', 'nl', 'Live'),
('lbl_load_more', 'nl', 'Meer laden'),
('lbl_location', 'nl', 'Lokatie'),
('lbl_locations', 'nl', 'Lokaties'),
('lbl_lock', 'nl', 'Vergrendel'),
('lbl_locked', 'nl', 'Op Slot'),
('lbl_log', 'nl', 'Log'),
('lbl_logging', 'nl', 'Logging'),
('lbl_login', 'nl', 'Login'),
('lbl_login_recover', 'nl', 'Verloren Login'),
('lbl_login_welcome', 'nl', 'Kies Wachtwoord'),
('lbl_logout', 'nl', 'Uitloggen'),
('lbl_main', 'nl', 'Hoofd'),
('lbl_manage', 'nl', 'Beheer'),
('lbl_manual', 'nl', 'Handmatig'),
('lbl_map', 'nl', 'Kaart'),
('lbl_mark', 'nl', 'Markeer'),
('lbl_marked', 'nl', 'Gemarkeerd'),
('lbl_masked', 'nl', 'Maskeerd'),
('lbl_master_page', 'nl', 'Master Pagina'),
('lbl_media', 'nl', 'Media'),
('lbl_media_replace_occurrences', 'nl', 'Vervang Voorvallen Met'),
('lbl_media_type', 'nl', 'Mediatype'),
('lbl_merge', 'nl', 'Voeg Samen'),
('lbl_message', 'nl', 'Bericht'),
('lbl_message_all', 'nl', 'Bericht Iedereen'),
('lbl_message_all_individual', 'nl', 'Bericht Iedereen (Individueel)'),
('lbl_message_count', 'nl', 'Lengte'),
('lbl_message_new', 'nl', 'Nieuw Bericht'),
('lbl_message_personal', 'nl', 'Persoonlijk Bericht'),
('lbl_message_system', 'nl', 'Systeembericht'),
('lbl_message_type', 'nl', 'Berichttype'),
('lbl_messaging', 'nl', 'Berichten'),
('lbl_messaging_email_me', 'nl', 'Email Mij'),
('lbl_messaging_new', 'nl', 'Nieuwe Berichten'),
('lbl_mode', 'nl', 'Modus'),
('lbl_model', 'nl', 'Model'),
('lbl_module', 'nl', 'Module'),
('lbl_modules', 'nl', 'Modules'),
('lbl_modules_installed', 'nl', 'Modules Geïnstalleerd'),
('lbl_month', 'nl', 'Maand'),
('lbl_multi_select', 'nl', 'Meervoudige Selectie'),
('lbl_multiple', 'nl', 'Meerdere'),
('lbl_multiply', 'nl', 'Vermenigvuldig'),
('lbl_multiply_with', 'nl', 'Vermenigvuldig met'),
('lbl_name', 'nl', 'Naam'),
('lbl_name_display', 'nl', 'Zichtbare Naam'),
('lbl_name_insertion', 'nl', 'Tussenvoegsel'),
('lbl_network', 'nl', 'Netwerk'),
('lbl_new', 'nl', 'Nieuw'),
('lbl_next', 'nl', 'Volgende'),
('lbl_no', 'nl', 'Nee'),
('lbl_no_effect', 'nl', 'Geen Effect'),
('lbl_no_name', 'nl', 'Zonder Naam'),
('lbl_node', 'nl', 'Node'),
('lbl_nodes', 'nl', 'Nodes'),
('lbl_none', 'nl', 'Geen'),
('lbl_normalised', 'nl', 'Genormaliseerd'),
('lbl_not_empty', 'nl', 'Niet Leeg'),
('lbl_notification', 'nl', 'Notificatie'),
('lbl_obfuscate', 'nl', 'Verduisteren'),
('lbl_object', 'nl', 'Object'),
('lbl_object_interaction_object', 'nl', 'Object'),
('lbl_object_interaction_objects', 'nl', 'Objecten'),
('lbl_object_interaction_stage', 'nl', 'Overzichtsscherm'),
('lbl_object_interaction_stages', 'nl', 'Overzichtsschermen'),
('lbl_objects', 'nl', 'Objecten'),
('lbl_offset', 'nl', 'Offset'),
('lbl_opacity', 'nl', 'Opacity'),
('lbl_open_site', 'nl', 'Site'),
('lbl_opt_out', 'nl', 'Opt Out'),
('lbl_optional', 'nl', 'Optioneel'),
('lbl_options', 'nl', 'Opties'),
('lbl_order', 'nl', 'Rangschikken'),
('lbl_organise', 'nl', 'Organiseren'),
('lbl_other', 'nl', 'Overig'),
('lbl_output', 'nl', 'Uitvoer'),
('lbl_overview', 'nl', 'Overzicht'),
('lbl_page', 'nl', 'Pagina'),
('lbl_page_clearance', 'nl', 'Paginabevoegdheid'),
('lbl_pages', 'nl', 'Pagina\'s'),
('lbl_parent', 'nl', 'Ascendent'),
('lbl_parent_name', 'nl', 'Ascendent Naam'),
('lbl_participants', 'nl', 'Deelnemers'),
('lbl_passkey', 'nl', 'Sleutel'),
('lbl_passkey_regenerate', 'nl', 'Genereer Nieuwe Sleutel'),
('lbl_password', 'nl', 'Wachtwoord'),
('lbl_password_reset', 'nl', 'Reset Wachtwoord'),
('lbl_past', 'nl', 'Verleden'),
('lbl_path', 'nl', 'Pad'),
('lbl_performance', 'nl', 'Prestatie'),
('lbl_period', 'nl', 'Periode'),
('lbl_personal', 'nl', 'Persoonlijk'),
('lbl_phone', 'nl', 'Telefoon'),
('lbl_ping', 'nl', 'Ping'),
('lbl_pingback', 'nl', 'Pingback'),
('lbl_poll', 'nl', 'Poll'),
('lbl_poll_sets', 'nl', 'Poll Groepen'),
('lbl_polls', 'nl', 'Polls'),
('lbl_popup', 'nl', 'Popup'),
('lbl_position', 'nl', 'Positie'),
('lbl_posted_by', 'nl', 'Geplaatst Door'),
('lbl_prefix', 'nl', 'Voorvoegen'),
('lbl_present', 'nl', 'Heden'),
('lbl_previous', 'nl', 'Vorige'),
('lbl_price', 'nl', 'Prijs'),
('lbl_print', 'nl', 'Print'),
('lbl_private', 'nl', 'Persoonlijk'),
('lbl_product', 'nl', 'Product'),
('lbl_project', 'nl', 'Project'),
('lbl_projects', 'nl', 'Projecten'),
('lbl_properties', 'nl', 'Eigenschappen'),
('lbl_publish', 'nl', 'Publiceer'),
('lbl_read_more', 'nl', 'Lees verder'),
('lbl_recipients', 'nl', 'Ontvangers'),
('lbl_redirect_page', 'nl', 'Redirect Pagina'),
('lbl_reference', 'nl', 'Verwijzing'),
('lbl_referenced', 'nl', 'Verwezen'),
('lbl_references', 'nl', 'Verwijzing'),
('lbl_referencing', 'nl', 'Verwijzingen'),
('lbl_referral_url', 'nl', 'Verwijzing URL'),
('lbl_register', 'nl', 'Registreer'),
('lbl_relate', 'nl', 'Relateer'),
('lbl_relation', 'nl', 'Relatie'),
('lbl_relative', 'nl', 'Relatief'),
('lbl_remark', 'nl', 'Opmerking'),
('lbl_remarks', 'nl', 'Opmerkingen'),
('lbl_reminder', 'nl', 'Herinnering'),
('lbl_remove', 'nl', 'Verwijder'),
('lbl_remove_empty', 'nl', 'Verwijder Lege'),
('lbl_replace', 'nl', 'Vervang'),
('lbl_reply', 'nl', 'Antwoord'),
('lbl_required', 'nl', 'Vereist'),
('lbl_reset', 'nl', 'Reset'),
('lbl_response', 'nl', 'Antwoord'),
('lbl_restore', 'nl', 'Herstellen'),
('lbl_result', 'nl', 'Resultaat'),
('lbl_run', 'nl', 'Uitvoeren'),
('lbl_run_web_service', 'nl', 'Draai Web Service'),
('lbl_running', 'nl', 'Lopend'),
('lbl_save', 'nl', 'Sla Op'),
('lbl_scale', 'nl', 'Schaal'),
('lbl_scenario', 'nl', 'Scenario'),
('lbl_scenarios', 'nl', 'Scenarios'),
('lbl_scope', 'nl', 'Bereik'),
('lbl_script', 'nl', 'Script'),
('lbl_script_hover', 'nl', 'Muisscript'),
('lbl_scroll_horizontal', 'nl', 'Horizontaal Scrollen'),
('lbl_scroll_vertical', 'nl', 'Verticaal Scrollen'),
('lbl_search', 'nl', 'Zoeken'),
('lbl_select', 'nl', 'Selecteer'),
('lbl_select_all', 'nl', 'Selecteer Alle'),
('lbl_select_or_store', 'nl', 'Selecteer Of Sla Op'),
('lbl_selection', 'nl', 'Selectie'),
('lbl_send', 'nl', 'Verstuur'),
('lbl_send_calendar_event_reminders', 'nl', 'Verstuur Herinneringen Agendapunten'),
('lbl_server_file', 'nl', 'Bestandsserver'),
('lbl_server_file_sync', 'nl', 'Synchroniseer Bestandsserver'),
('lbl_server_host', 'nl', 'Host'),
('lbl_server_host_port', 'nl', 'Poort'),
('lbl_server_hosts', 'nl', 'Hosts'),
('lbl_servers', 'nl', 'Servers'),
('lbl_service', 'nl', 'Dienst'),
('lbl_set', 'nl', 'Plaats'),
('lbl_settings', 'nl', 'Instellingen'),
('lbl_shape', 'nl', 'Vorm'),
('lbl_shape_circle', 'nl', 'Cirkel'),
('lbl_shape_square', 'nl', 'Vierkant'),
('lbl_share', 'nl', 'Deel'),
('lbl_show', 'nl', 'Toon'),
('lbl_show_404', 'nl', 'Toon 404'),
('lbl_show_all', 'nl', 'Toon Alles'),
('lbl_show_menu', 'nl', 'Toon Menu'),
('lbl_show_system_errors', 'nl', 'Toon Systeemerrors'),
('lbl_siblings', 'nl', 'Naasten'),
('lbl_signup', 'nl', 'Inschrijven'),
('lbl_site_attribution', 'nl', '<a href=\"[S][BASE_URL]\" target=\"_blank\">[D][name]</a>'),
('lbl_size', 'nl', 'Grootte'),
('lbl_size_max', 'nl', 'Max Grootte'),
('lbl_size_min', 'nl', 'Min Grootte'),
('lbl_slide', 'nl', 'Slide'),
('lbl_sliders', 'nl', 'Sliders'),
('lbl_slides', 'nl', 'Slides'),
('lbl_source', 'nl', 'Bron'),
('lbl_source_abbr', 'nl', 'Src'),
('lbl_sources', 'nl', 'Bronnen'),
('lbl_span', 'nl', 'Overspannen'),
('lbl_specify', 'nl', 'Specificeer'),
('lbl_start', 'nl', 'Start'),
('lbl_start_over', 'nl', 'Begin Opnieuw'),
('lbl_statistics', 'nl', 'Statistiek'),
('lbl_status', 'nl', 'Status'),
('lbl_storage', 'nl', 'Opslag'),
('lbl_style', 'nl', 'Stijl'),
('lbl_style_hover', 'nl', 'Muisstijl'),
('lbl_subject', 'nl', 'Onderwerp'),
('lbl_submissions', 'nl', 'Inzendingen'),
('lbl_summary', 'nl', 'Samenvatting'),
('lbl_tag', 'nl', 'Tag'),
('lbl_tag_cloud', 'nl', 'Tag Cloud'),
('lbl_tags', 'nl', 'Tags'),
('lbl_tags_show_all', 'nl', 'Toon More'),
('lbl_target', 'nl', 'Doel'),
('lbl_task', 'nl', 'Taak'),
('lbl_technical', 'nl', 'Technisch'),
('lbl_template', 'nl', 'Template'),
('lbl_templates', 'nl', 'Templates'),
('lbl_text', 'nl', 'Tekst'),
('lbl_text_bold', 'nl', '<strong>Vet</strong>'),
('lbl_text_color', 'nl', 'Tekstkleur'),
('lbl_text_emphasis', 'nl', 'Tekstopmaak'),
('lbl_text_italic', 'nl', '<em>Cursief</em>'),
('lbl_text_strikethrough', 'nl', '<del>Doorgestreept</del>'),
('lbl_theme', 'nl', 'Thema'),
('lbl_threshold', 'nl', 'Drempelwaarde'),
('lbl_time', 'nl', 'Tijd'),
('lbl_timeout', 'nl', 'Timeout'),
('lbl_timing', 'nl', 'Timing'),
('lbl_title', 'nl', 'Titel'),
('lbl_to', 'nl', 'Naar'),
('lbl_total', 'nl', 'Totaal'),
('lbl_transition_effect', 'nl', 'Overgangseffect'),
('lbl_transition_speed', 'nl', 'Overgangssnelheid'),
('lbl_twitter', 'nl', 'Twitter'),
('lbl_type', 'nl', 'Type'),
('lbl_types', 'nl', 'Types'),
('lbl_uname', 'nl', 'Gebruikersnaam'),
('lbl_unchanged', 'nl', 'Onveranderd'),
('lbl_unique', 'nl', 'Uniek'),
('lbl_unknown', 'nl', 'Onbekend'),
('lbl_update', 'nl', 'Update'),
('lbl_upload', 'nl', 'Upload'),
('lbl_uri_translator', 'nl', 'URI Vertaaldienst'),
('lbl_uri_translators', 'nl', 'URI Vertaaldiensten'),
('lbl_uris', 'nl', 'URIs'),
('lbl_url', 'nl', 'URL'),
('lbl_usage', 'nl', 'Gebruik'),
('lbl_use', 'nl', 'Gebruik'),
('lbl_use_servers', 'nl', 'Gebruik Servers'),
('lbl_user', 'nl', 'Gebruiker'),
('lbl_user_domain', 'nl', 'Domein'),
('lbl_user_group', 'nl', 'Gebruikersgroep'),
('lbl_user_groups', 'nl', 'Gebruikersgroepen'),
('lbl_user_my_default', 'nl', 'Mijn Standaard Instellingen'),
('lbl_username', 'nl', 'Gebruikersnaam'),
('lbl_users', 'nl', 'Gebruikers'),
('lbl_valid_period', 'nl', 'Geldigheidsduur'),
('lbl_value', 'nl', 'Waarde'),
('lbl_values', 'nl', 'Waarden'),
('lbl_vat', 'nl', 'BTW'),
('lbl_version', 'nl', 'Versie'),
('lbl_version_abbr', 'nl', 'Ver'),
('lbl_view', 'nl', 'Bekijk'),
('lbl_view_selection', 'nl', 'Toon Selectie'),
('lbl_visibility', 'nl', 'Zichtbaarheid'),
('lbl_visible', 'nl', 'Zichtbaar'),
('lbl_vote', 'nl', 'Stem'),
('lbl_votes', 'nl', 'Stemmen'),
('lbl_weight', 'nl', 'Zwaarte'),
('lbl_welcome', 'nl', 'Welkom'),
('lbl_widgets', 'nl', 'Widgets'),
('lbl_width', 'nl', 'Breedte'),
('lbl_width_max', 'nl', 'Max Breedte'),
('lbl_width_min', 'nl', 'Min Breedte'),
('lbl_word_count', 'nl', 'Woordaantal'),
('lbl_workspace', 'nl', 'Werkruimte'),
('lbl_workspaces', 'nl', 'Werkruimtes'),
('lbl_year', 'nl', 'Jaar'),
('lbl_yes', 'nl', 'Ja'),
('lbl_youtube', 'nl', 'Youtube'),
('lbl_zipcode', 'nl', 'Postcode'),
('lbl_zoom_auto', 'nl', 'Automatische Zoom'),
('lbl_zoom_default', 'nl', 'Zoom Standaard'),
('lbl_zoom_level', 'nl', 'Zoomniveau'),
('lbl_zoom_levels', 'nl', 'Zoom Niveaus'),
('lbl_zoom_max', 'nl', 'Zoom Max'),
('lbl_zoom_min', 'nl', 'Zoom Min'),
('lnk_archive', 'nl', 'Bekijk Archief'),
('mail_account_changed', 'nl', '<p>Beste [V][name],</p>\n<p>Jouw accountgegevens voor [D][name] zijn aangepast.</p>\n<p>De gegevens zijn nu als volgt:</p>\n<p>\nGebruikersnaam: [V][user_name]<br />\nDomein: [V][domain]\n</p>'),
('mail_account_changed_title', 'nl', 'Accountgegevens voor [D][name] zijn aangepast.'),
('mail_account_login_url', 'nl', '<p>Volg <a href=\"[V][url]\" target=\"_blank\">deze link</a> om in te loggen.</p>'),
('mail_account_login_url_expire', 'nl', '<p>Volg <a href=\"[V][url]\" target=\"_blank\">deze link</a> ([L][msg_link_expire]) om in te loggen.</p>'),
('mail_account_new', 'nl', '<p>Beste [V][name],</p>\n<p>Jouw accountgegevens voor [D][name] zijn aangemaakt.</p>\n<p>Met de volgende gegevens kan je inloggen:</p>\n<p>\nGebruikersnaam: [V][user_name]<br />\nDomein: [V][domain]\n</p>'),
('mail_account_new_title', 'nl', 'Accountgegevens voor [D][name].'),
('mail_confirm_account', 'nl', '<p>Beste [V][name],</p>\n<p>Uw [D][name]-account is aangemaakt.</p>\n<p>Volg <a href=\"[V][url]\">deze link</a> ([L][msg_link_expire]) om uw registratie te bevestigen.</p>'),
('mail_confirm_account_recover', 'nl', '<p>Beste [V][name],</p>\n<p>Een nieuw wachtwoord is aangevraagd voor uw account op [D][name].</p>\n<p>Volg <a href=\"[V][url]\">deze link</a> ([L][msg_link_expire]) om uw aanvraag voor een nieuw wachtwoord te bevestigen.</p>'),
('mail_confirm_account_recover_title', 'nl', 'Aanvraag nieuw wachtwoord voor [D][name].'),
('mail_confirm_account_title', 'nl', 'Bevestig uw accountgegevens voor [D][name].'),
('mail_confirm_account_update', 'nl', '<p>Beste [V][name],</p>\n<p>Jouw account op [D][name] is aangepast.</p>\n<p>Volg <a href=\"[V][url]\">deze link</a> om deze veranderingen te bevestigen.</p>'),
('mail_confirm_account_update_title', 'nl', 'Verandering accountgegevens voor [D][name].'),
('mail_form_submitted', 'nl', 'Er is een formulier verzonden op de [D][name] website, ga naar het <a href=\"[V][url]\">CMS</a> om de inzending te bekijken.'),
('mail_messaging_notification', 'nl', '<p>Beste [V][name],</p>\n<p>Je hebt een nieuw bericht ontvangen van [D][name]. Het bericht bevindt zich in jouw inbox onder het onderwerp \"[V][subject]\"</p>\n<p>Klik <a href=\"[V][link]\">hier</a> om direct naar je inbox te gaan.</p>'),
('mail_messaging_notification_title', 'nl', 'Je hebt een nieuw bericht ontvangen op [D][name].'),
('msg_access_denied', 'nl', 'Je beschikt niet over de juiste bevoegheden om toegang te krijgen.'),
('msg_access_limit', 'nl', 'De limiet voor het aantal foutieve logins is bereikt, probeer het later opnieuw.'),
('msg_account_update_confirmed', 'nl', 'Jouw nieuwe accountgegevens zijn bevestigd.'),
('msg_api_limit', 'nl', 'De request-limiet voor de API is bereikt ([V][limit]). Probeer het later nog eens.'),
('msg_building_cache', 'nl', 'De cache wordt opgebouwd'),
('msg_calendar_event_reminder_notification', 'nl', 'Dit is een herinnering voor het agendapunt [V][name] welke start op [V][date] en eindigt [V][date_end].\nHet agendapunt begint over [V][reminder_amount] [V][reminder_unit_name].\n\n[V][description]'),
('msg_confirm_account_mail_sent', 'nl', 'Een bevestiging is naar uw emailadres verstuurd.'),
('msg_confirm_account_recover_mail_sent', 'nl', 'Een email is naar uw account verzonden om uw verloren informatie te herstellen.'),
('msg_confirm_account_update_mail_sent', 'nl', 'Een bevestigingsemail is naar jouw emailadres gestuurd.'),
('msg_contact_mail_sent', 'nl', 'Contactformulier is succesvol verstuurd: [V][from] ([V][email])'),
('msg_data_range_too_wide', 'nl', 'De huidige dataselectie is te breed, gelieve de selectie kleiner te maken.'),
('msg_date_incorrect', 'nl', 'Datum is incorrect.'),
('msg_duplicate_user', 'nl', 'Deze gebruiker bestaat al, gelieve een andere gebruikersnaam te kiezen.'),
('msg_email_opt_out_success', 'nl', 'U bent succesvol uitgeschreven.'),
('msg_enable_cookies', 'nl', 'Jouw sessie is mogelijk verlopen. Ververs de pagina (F5) of klik <a href=\"[V][url]\">hier</a> om opnieuw te starten.'),
('msg_enable_script', 'nl', 'Probeer om ondersteuning voor javascript in de browser in te schakelen.'),
('msg_error', 'nl', 'De acties zijn niet uitgevoerd door toedoen van een error'),
('msg_error_database_data_field_limit', 'nl', 'De database heeft een waarde uit jouw data ontvangen dat te groot is om op te slaan. Controleer de groottes van de waarden die je verstuurt.'),
('msg_error_email_format', 'nl', 'Het ingegeven emailadres is niet een juist adres.'),
('msg_error_memory_limit', 'nl', 'De toegestane geheugengrootte van jouw verzoek heeft de limiet van <strong>[V][amount]</strong> bereikt. Probeer jouw verzoek te herzien, of neem contact op met [D][email] om onregelmatigheden te rapporteren.'),
('msg_error_time_limit', 'nl', 'De toegestane uitvoeringstijd van jouw verzoek heeft de limiet van <strong>[V][amount] seconden</strong> bereikt. Probeer jouw verzoek te herzien, of neem contact op met [D][email] om onregelmatigheden te rapporteren.'),
('msg_file_too_large', 'nl', 'Bestand is te groot.'),
('msg_file_upload_successful', 'nl', 'Bestand is succesvol geüpload.'),
('msg_form_submitted', 'nl', 'Formulier is succesvol verzonden.'),
('msg_illegal_action', 'nl', 'De huidige actie kon door foutieve waardes niet uitgevoerd worden.'),
('msg_invalid_email', 'nl', 'Ongeldige emailadres.'),
('msg_invalid_file_type', 'nl', 'Geen geldig bestandstype.'),
('msg_invalid_file_type_specific', 'nl', 'Geen geldig bestandstype. Een bestand van het type <strong>[V][type]</strong> is benodigd.'),
('msg_item_already_exists', 'nl', 'Het item bestaat al.'),
('msg_link_expire', 'nl', 'link vervalt wanneer deze wordt geklikt'),
('msg_loading_server_data', 'nl', 'Laden van serverdata.'),
('msg_login_incorrect', 'nl', 'Verkeerde gebruikersnaam of wachtwoord.'),
('msg_login_recover_confirm', 'nl', '[L][msg_login_welcome]'),
('msg_login_recover_confirmed', 'nl', '[L][msg_login_welcome_confirmed]'),
('msg_login_recover_link', 'nl', 'Wachtwoord kwijt? Klik <a href=\"[V][url_recover_password]\">hier</a>.'),
('msg_login_recover_link_return', 'nl', 'Klik <a href=\"[V][url_login]\">hier</a> om terug te gaan naar het loginformulier.'),
('msg_login_welcome', 'nl', '<p>Hi [V][name],</p>\n<p>Hieronder volgen de basisgegevens voor jouw [D][name]-account:</p>\n<ul>\n<li>Gebruikersnaam: [V][user_name]</li>\n<li>Email: [V][user_email]</li>\n<li>Domein: [V][domain]</li>\n</ul>\n<p>Voer het door jou gewenste wachtwoord in:</p>'),
('msg_login_welcome_confirmed', 'nl', 'Jouw wachtwoord is bevestigd. Gebruik jouw gebruikersnaam en wachtwoord om te loggen.'),
('msg_missing_information', 'nl', 'Benodigde informatie mist of is niet correct aangeleverd.'),
('msg_no', 'nl', 'Er zijn geen [V][name] beschikbaar.'),
('msg_no_blogs', 'nl', 'Er zijn nog geen blogs aangemaakt.'),
('msg_no_calendar_events', 'nl', 'Er zijn geen agendapunten.'),
('msg_no_cookie_support', 'nl', 'Er is geen ondersteuning voor cookies gevonden'),
('msg_no_custom_content', 'nl', 'Er is nog geen eigen content aangemaakt.'),
('msg_no_dashboards', 'nl', 'Er zijn nog geen dashboard\'s aangemaakt.'),
('msg_no_data', 'nl', 'Geen data.'),
('msg_no_directories', 'nl', 'Er is nog geen directorystructuur aangemaakt.'),
('msg_no_file_or_too_large', 'nl', 'Geen bestand geüpload, of bestand is te groot (Max. [V][max_size] MB)'),
('msg_no_forms', 'nl', 'Er zijn nog geen formulieren aangemaakt.'),
('msg_no_language', 'nl', 'Er zijn nog geen taalprofielen aangemaakt.'),
('msg_no_media', 'nl', 'Er zijn nog geen media items aangemaakt.'),
('msg_no_object_interaction_objects', 'nl', 'Er zijn nog geen objecten aangemaakt.'),
('msg_no_object_interaction_stages', 'nl', 'Er zijn nog geen overzichtsschermen aangemaakt.'),
('msg_no_options', 'nl', 'Er zijn geen opties beschikbaar.'),
('msg_no_pages', 'nl', 'Geen pagina\'s gevonden.'),
('msg_no_pingbacks', 'nl', 'Geen pingback\'s gevonden'),
('msg_no_polls', 'nl', 'Er zijn nog geen poll\'s aangemaakt.'),
('msg_no_projects', 'nl', 'Er zijn nog geen projecten aangemaakt.'),
('msg_no_results', 'nl', 'Geen resultaten.'),
('msg_no_script_support', 'nl', 'Er is geen ondersteuning voor javascript gevonden.'),
('msg_no_sliders', 'nl', 'Er zijn nog geen sliders aangemaakt.'),
('msg_no_slides', 'nl', 'Er zijn nog geen slides aangemaakt.'),
('msg_no_templates', 'nl', 'Er zijn nog geen templates aangemaakt.'),
('msg_no_user_groups', 'nl', 'Er zijn nog geen gebruikersgroepen aangemaakt.'),
('msg_no_users', 'nl', 'Er zijn nog geen gebruikers aangemaakt.'),
('msg_not_allowed', 'nl', 'De huidige actie is niet toegestaan.'),
('msg_not_allowed_demo', 'nl', 'De huidige actie is niet toegestaan met een demo-account.'),
('msg_not_available', 'nl', 'Niet beschikbaar.'),
('msg_not_found', 'nl', 'Het opgevraagde item is niet gevonden.'),
('msg_object_interaction_tiles_level_done', 'nl', 'Nieuw zoomniveau is aangemaakt:'),
('msg_page_delete_is_index_fallback', 'nl', 'Pagina kan niet verwijderd worden door een index- of terugvaleigenschap.'),
('msg_page_not_found', 'nl', 'De pagina die je opvroeg kan niet gevonden worden'),
('msg_page_not_found_suggestion', 'nl', 'Probeer terug te gaan naar de pagina waar je vandaan kwam of klik <a href=\"[V][url]\">hier</a>'),
('msg_redirect', 'nl', 'Je wordt naar een ander adres gestuurd.'),
('msg_registration_confirmed', 'nl', 'Uw account is bevestigd.'),
('msg_search_by_typing', 'nl', 'Typ om te zoeken binnen [V][what].'),
('msg_search_no_result', 'nl', 'De zoekactie heeft geen resultaten gevonden.'),
('msg_search_too_short', 'nl', 'De zoekopdracht is te kort, een minimum van 4 karakters is wenselijk.'),
('msg_site_maintenance', 'nl', '[D][name] is in onderhoud.'),
('msg_site_read_only', 'nl', 'Je kijkt momenteel naar een ALLEEN-LEZEN versie van [D][name]!'),
('msg_success', 'nl', 'De actie is met succes voltooid.'),
('msg_transferring', 'nl', 'Versturen...'),
('msg_upload_failed', 'nl', 'Upload mislukt.'),
('msg_wait', 'nl', 'Een moment alstublieft.'),
('ttl_archive', 'nl', 'Archief'),
('ttl_blog', 'nl', 'Blog'),
('ttl_blog_posts', 'nl', 'Blog Posts'),
('ttl_blog_preview', 'nl', 'Blog Preview'),
('ttl_blogs', 'nl', 'Blogs'),
('ttl_calendar', 'nl', 'Kalender'),
('ttl_checklists', 'nl', 'Checklijsten'),
('ttl_cms', 'nl', 'CMS'),
('ttl_cms_users', 'nl', 'CMS Gebruikers'),
('ttl_comments', 'nl', 'Reacties'),
('ttl_contact', 'nl', 'Contact'),
('ttl_content', 'nl', 'Content'),
('ttl_custom_content', 'nl', 'Custom Content'),
('ttl_dashboard', 'nl', 'Dashboard'),
('ttl_dashboards', 'nl', 'Dashboards'),
('ttl_data', 'nl', 'Data'),
('ttl_details', 'nl', 'Informatie'),
('ttl_directories', 'nl', 'Directories'),
('ttl_email_manager', 'nl', 'Email Manager'),
('ttl_footer', 'nl', 'Footer'),
('ttl_form', 'nl', 'Formulier'),
('ttl_forms', 'nl', 'Formulieren'),
('ttl_header', 'nl', 'Header'),
('ttl_header_dropdown', 'nl', 'Header Dropdown'),
('ttl_input', 'nl', 'Invoer'),
('ttl_invoice', 'nl', 'Factuur'),
('ttl_jobs', 'nl', 'Taken'),
('ttl_labels', 'nl', 'Labels'),
('ttl_language', 'nl', 'Taal'),
('ttl_latest_blog_posts', 'nl', 'Laatste Blog Posts'),
('ttl_media', 'nl', 'Media'),
('ttl_messaging', 'nl', 'Berichten'),
('ttl_navigation', 'nl', 'Navigatie'),
('ttl_newsletter_signup', 'nl', 'Inschrijven Nieuwsbrief'),
('ttl_newsletters', 'nl', 'Nieuwsbrieven'),
('ttl_object_interaction', 'nl', 'Overzichtsschermen'),
('ttl_order', 'nl', 'Bestellen'),
('ttl_orders', 'nl', 'Bestellingen'),
('ttl_poll', 'nl', 'Poll'),
('ttl_poll_sets', 'nl', 'Poll Groepen'),
('ttl_polls', 'nl', 'Polls'),
('ttl_posts', 'nl', 'Posts'),
('ttl_project_management', 'nl', 'Project Management'),
('ttl_projects', 'nl', 'Projecten'),
('ttl_register', 'nl', 'Registreren'),
('ttl_register_users', 'nl', 'Registreer Gebruikers'),
('ttl_result', 'nl', 'Resultaat'),
('ttl_search', 'nl', 'Zoeken'),
('ttl_search_box', 'nl', 'Zoekveld'),
('ttl_settings', 'nl', 'Instellingen'),
('ttl_shop', 'nl', 'Shop'),
('ttl_shop_orders', 'nl', 'Shop Bestellingen'),
('ttl_shop_products', 'nl', 'Shop Producten'),
('ttl_site', 'nl', 'Site'),
('ttl_sitemap', 'nl', 'Sitemap'),
('ttl_slider', 'nl', 'Slider'),
('ttl_sliders', 'nl', 'Sliders'),
('ttl_slides', 'nl', 'Slides'),
('ttl_tags', 'nl', 'Tags'),
('ttl_templates', 'nl', 'Templates'),
('ttl_upload', 'nl', 'Upload'),
('ttl_user_groups', 'nl', 'Gebruikersgroepen'),
('ttl_user_management', 'nl', 'Gebruikersbeheer'),
('ttl_website_details', 'nl', 'Website Details'),
('txt_contact_form_info', 'nl', 'Als u vragen, opmerkingen of suggesties heeft voor [D][name], gebruik dan a.u.b. het onderstaande formulier.'),
('txt_email_opt_out', 'nl', '<p>Klik <a href=\"[V][link_opt_out]\">hier</a> om u uit te schrijven.</p>'),
('txt_newsletter_signup', 'nl', 'Abboneer uzelf op de [D][name] nieuwsbrief.'),
('txt_trouble_viewing', 'nl', 'Dit bericht is niet goed te zien? Klik <a href=\"[V][link_view]\">hier</a>.'),
('unit_data_boolean', 'nl', 'Juist/Onjuist'),
('unit_data_date', 'nl', 'Datum'),
('unit_data_int', 'nl', 'Getal'),
('unit_data_text', 'nl', 'Tekst'),
('unit_data_varchar', 'nl', 'String'),
('unit_data_xml', 'nl', 'XML'),
('unit_day', 'nl', 'dag'),
('unit_days', 'nl', 'dagen'),
('unit_hour', 'nl', 'uur'),
('unit_hours', 'nl', 'uur'),
('unit_meter', 'nl', 'meter'),
('unit_milliseconds', 'nl', 'milliseconden'),
('unit_minute', 'nl', 'minuut'),
('unit_minutes', 'nl', 'minuten'),
('unit_month', 'nl', 'maand'),
('unit_month_april', 'nl', 'april'),
('unit_month_august', 'nl', 'augustus'),
('unit_month_december', 'nl', 'december'),
('unit_month_february', 'nl', 'februari'),
('unit_month_january', 'nl', 'januari'),
('unit_month_july', 'nl', 'juli'),
('unit_month_june', 'nl', 'juni'),
('unit_month_march', 'nl', 'maart'),
('unit_month_may', 'nl', 'mei'),
('unit_month_november', 'nl', 'november'),
('unit_month_october', 'nl', 'oktober'),
('unit_month_september', 'nl', 'september'),
('unit_months', 'nl', 'maanden'),
('unit_second', 'nl', 'seconde'),
('unit_seconds', 'nl', 'seconden'),
('unit_week', 'nl', 'week'),
('unit_week_day_abbr_length', 'nl', '2'),
('unit_week_friday', 'nl', 'Vrijdag'),
('unit_week_monday', 'nl', 'Maandag'),
('unit_week_saturday', 'nl', 'Zaterdag'),
('unit_week_sunday', 'nl', 'Zondag'),
('unit_week_thursday', 'nl', 'Donderdag'),
('unit_week_tuesday', 'nl', 'Dinsdag'),
('unit_week_wednesday', 'nl', 'Woensdag'),
('unit_weeks', 'nl', 'weken'),
('unit_year', 'nl', 'jaar');
